-- Full runtime Supabase RPC schema/runtime script
-- Run in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- ============================================================================
-- Tables
-- ============================================================================

create table if not exists public.users_directory (
  id bigint generated by default as identity primary key,
  department text not null,
  employee_name text not null,
  access_code_hash text not null,
  email text default '',
  changed_at timestamptz not null default now(),
  changed_by text default '',
  source text default 'migration',
  active boolean not null default true,
  unique (department, employee_name)
);

create index if not exists idx_users_directory_lookup
  on public.users_directory (department, employee_name, active);

create table if not exists public.admins_directory (
  id bigint generated by default as identity primary key,
  admin_name text not null unique,
  admin_code_hash text not null,
  role text not null default 'Admin',
  allowed_departments_json jsonb not null default '["All"]'::jsonb,
  changed_at timestamptz not null default now(),
  changed_by text default '',
  source text default 'migration',
  active boolean not null default true
);

create index if not exists idx_admins_directory_lookup
  on public.admins_directory (admin_name, active);

create table if not exists public.task_submissions (
  id bigint generated by default as identity primary key,
  request_id text unique,
  stage text not null check (stage in ('SOD', 'EOD')),
  submitted_at timestamptz not null default now(),
  work_date date not null,
  department text not null,
  employee_name text not null,
  access_code text,
  task_count integer not null default 0,
  total_spent_minutes integer not null default 0,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_task_submissions_lookup
  on public.task_submissions (department, employee_name, stage, work_date, submitted_at);

create index if not exists idx_task_submissions_work_date
  on public.task_submissions (work_date);

create index if not exists idx_task_submissions_stage_work_date
  on public.task_submissions (stage, work_date, submitted_at desc);

create index if not exists idx_task_submissions_canonical_lookup
  on public.task_submissions (
    stage,
    regexp_replace(lower(coalesce(department, '')), '[^a-z]', '', 'g'),
    lower(trim(employee_name)),
    work_date,
    submitted_at desc
  );

create index if not exists idx_task_submissions_dashboard_lookup
  on public.task_submissions (
    stage,
    work_date,
    public.canonical_department_key(department),
    lower(trim(employee_name)),
    submitted_at desc
  );

create table if not exists public.task_start_drafts (
  id bigint generated by default as identity primary key,
  work_date date not null,
  department text not null,
  employee_name text not null,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (work_date, department, employee_name)
);

create index if not exists idx_task_start_drafts_lookup
  on public.task_start_drafts (department, employee_name, work_date, updated_at desc);

create index if not exists idx_task_start_drafts_canonical_lookup
  on public.task_start_drafts (
    regexp_replace(lower(coalesce(department, '')), '[^a-z]', '', 'g'),
    lower(trim(employee_name)),
    work_date,
    updated_at desc
  );

create table if not exists public.task_admin_events (
  id bigint generated by default as identity primary key,
  event_key text unique,
  event_type text not null check (event_type in ('assignment', 'recurring', 'planner_task', 'planner_consumed', 'cliq_webhook', 'carryover_removed', 'carryover_renamed', 'attendance_override')),
  changed_at timestamptz not null default now(),
  work_date date,
  department text not null,
  employee_name text not null,
  task_id text,
  title text,
  status text,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

do $$
begin
  if exists (
    select 1
    from pg_constraint c
    where c.conname = 'task_admin_events_event_type_check'
      and c.conrelid = 'public.task_admin_events'::regclass
  ) then
    alter table public.task_admin_events drop constraint task_admin_events_event_type_check;
  end if;
  alter table public.task_admin_events
    add constraint task_admin_events_event_type_check
    check (event_type in ('assignment', 'recurring', 'planner_task', 'planner_consumed', 'cliq_webhook', 'carryover_removed', 'carryover_renamed', 'attendance_override'));
exception
  when duplicate_object then null;
end $$;

create index if not exists idx_task_admin_events_lookup
  on public.task_admin_events (event_type, department, employee_name, work_date, changed_at);

create index if not exists idx_task_admin_events_type_date
  on public.task_admin_events (event_type, work_date, changed_at desc);

create index if not exists idx_task_admin_events_canonical_lookup
  on public.task_admin_events (
    event_type,
    regexp_replace(lower(coalesce(department, '')), '[^a-z]', '', 'g'),
    lower(trim(employee_name)),
    work_date,
    changed_at desc
  );

create index if not exists idx_task_admin_events_dashboard_lookup
  on public.task_admin_events (
    event_type,
    work_date,
    public.canonical_department_key(department),
    lower(trim(employee_name)),
    changed_at desc
  );

create index if not exists idx_task_admin_events_dashboard_changed_lookup
  on public.task_admin_events (
    event_type,
    public.canonical_department_key(department),
    lower(trim(employee_name)),
    changed_at desc
  );

create table if not exists public.task_approval_requests (
  id bigint generated by default as identity primary key,
  request_id text not null unique,
  parent_request_id text,
  work_date date not null,
  department text not null,
  requester_name text not null,
  source_task_id text default '',
  source_task_title text not null default '',
  source_task_priority text not null default 'Medium',
  source_completion_percent integer not null default 0,
  source_spent_minutes integer not null default 0,
  source_note text default '',
  chosen_approver_admin_name text not null,
  request_note text default '',
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  resolved_by text default '',
  resolved_at timestamptz,
  resolution_note text default '',
  reassigned_department text default '',
  reassigned_employee_name text default '',
  linked_assignment_event_key text default '',
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_task_approval_requests_lookup
  on public.task_approval_requests (chosen_approver_admin_name, status, created_at desc);

create index if not exists idx_task_approval_requests_requester
  on public.task_approval_requests (department, requester_name, created_at desc);

create index if not exists idx_task_approval_requests_canonical_lookup
  on public.task_approval_requests (
    regexp_replace(lower(coalesce(department, '')), '[^a-z]', '', 'g'),
    lower(trim(requester_name)),
    lower(trim(chosen_approver_admin_name)),
    status,
    created_at desc
  );

create table if not exists public.task_approval_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  request_id text not null,
  event_type text not null check (event_type in ('requested', 'approved', 'rejected', 'resubmitted', 'assigned', 'cancelled')),
  actor_name text default '',
  event_note text default '',
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_task_approval_events_request
  on public.task_approval_events (request_id, created_at desc);

create index if not exists idx_task_approval_events_type
  on public.task_approval_events (event_type, created_at desc);

create index if not exists idx_users_directory_active_canonical
  on public.users_directory (active, regexp_replace(lower(coalesce(department, '')), '[^a-z]', '', 'g'), lower(trim(employee_name)));

create table if not exists public.user_streaks (
  id bigint generated by default as identity primary key,
  department text not null,
  employee_name text not null,
  current_streak integer not null default 0,
  best_streak integer not null default 0,
  last_counted_date date,
  updated_at timestamptz not null default now(),
  unique (department, employee_name)
);

create index if not exists idx_user_streaks_lookup
  on public.user_streaks (department, employee_name);

create table if not exists public.leave_days (
  id bigint generated by default as identity primary key,
  leave_date date not null,
  department text not null,
  employee_name text not null,
  leave_status text not null default 'Leave',
  reason text default '',
  marked_by text default '',
  source text default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (leave_date, department, employee_name)
);

alter table public.leave_days add column if not exists leave_status text not null default 'Leave';
alter table public.leave_days add column if not exists reason text default '';
alter table public.leave_days add column if not exists marked_by text default '';
alter table public.leave_days add column if not exists source text default 'manual';
alter table public.leave_days add column if not exists created_at timestamptz not null default now();
alter table public.leave_days add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_leave_days_lookup
  on public.leave_days (leave_date, department, employee_name, leave_status);

-- ============================================================================
-- Security model (RPC-first)
-- ============================================================================

alter table public.users_directory enable row level security;
alter table public.admins_directory enable row level security;
alter table public.task_submissions enable row level security;
alter table public.task_start_drafts enable row level security;
alter table public.task_admin_events enable row level security;
alter table public.task_approval_requests enable row level security;
alter table public.task_approval_events enable row level security;
alter table public.user_streaks enable row level security;
alter table public.leave_days enable row level security;

-- No direct table policies for anon/authenticated.
-- Access should go through SECURITY DEFINER RPC functions.
