create table if not exists public.task_submissions (
  id bigint generated by default as identity primary key,
  request_id text unique,
  stage text not null check (stage in ('SOD', 'EOD')),
  submitted_at timestamptz not null default now(),
  work_date date not null,
  department text not null,
  employee_name text not null,
  access_code text,
  task_count integer not null default 0,
  total_spent_minutes integer not null default 0,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_task_submissions_lookup
  on public.task_submissions (department, employee_name, stage, work_date, submitted_at);

create index if not exists idx_task_submissions_work_date
  on public.task_submissions (work_date);

create table if not exists public.task_start_drafts (
  id bigint generated by default as identity primary key,
  work_date date not null,
  department text not null,
  employee_name text not null,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (work_date, department, employee_name)
);

create index if not exists idx_task_start_drafts_lookup
  on public.task_start_drafts (department, employee_name, work_date, updated_at desc);

-- Service-role based server writes are used from the server-side Supabase flow.
-- RLS can remain enabled with no public policies for this table.
alter table public.task_submissions enable row level security;
alter table public.task_start_drafts enable row level security;

create table if not exists public.task_admin_events (
  id bigint generated by default as identity primary key,
  event_key text unique,
  event_type text not null check (event_type in ('assignment', 'recurring', 'planner_task', 'planner_consumed')),
  changed_at timestamptz not null default now(),
  work_date date,
  department text not null,
  employee_name text not null,
  task_id text,
  title text,
  status text,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_task_admin_events_lookup
  on public.task_admin_events (event_type, department, employee_name, changed_at);

create index if not exists idx_task_admin_events_work_date
  on public.task_admin_events (event_type, department, employee_name, work_date);

alter table public.task_admin_events enable row level security;
