-- Full runtime cutover script (Apps Script -> Supabase RPC)
-- Run in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- ============================================================================
-- Tables
-- ============================================================================

create table if not exists public.users_directory (
  id bigint generated by default as identity primary key,
  department text not null,
  employee_name text not null,
  access_code_hash text not null,
  email text default '',
  changed_at timestamptz not null default now(),
  changed_by text default '',
  source text default 'migration',
  active boolean not null default true,
  unique (department, employee_name)
);

create index if not exists idx_users_directory_lookup
  on public.users_directory (department, employee_name, active);

create table if not exists public.admins_directory (
  id bigint generated by default as identity primary key,
  admin_name text not null unique,
  admin_code_hash text not null,
  role text not null default 'Admin',
  allowed_departments_json jsonb not null default '["All"]'::jsonb,
  changed_at timestamptz not null default now(),
  changed_by text default '',
  source text default 'migration',
  active boolean not null default true
);

create index if not exists idx_admins_directory_lookup
  on public.admins_directory (admin_name, active);

create table if not exists public.task_submissions (
  id bigint generated by default as identity primary key,
  request_id text unique,
  stage text not null check (stage in ('SOD', 'EOD')),
  submitted_at timestamptz not null default now(),
  work_date date not null,
  department text not null,
  employee_name text not null,
  access_code text,
  task_count integer not null default 0,
  total_spent_minutes integer not null default 0,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_task_submissions_lookup
  on public.task_submissions (department, employee_name, stage, work_date, submitted_at);

create index if not exists idx_task_submissions_work_date
  on public.task_submissions (work_date);

create index if not exists idx_task_submissions_stage_work_date
  on public.task_submissions (stage, work_date, submitted_at desc);

create index if not exists idx_task_submissions_canonical_lookup
  on public.task_submissions (
    stage,
    regexp_replace(lower(coalesce(department, '')), '[^a-z]', '', 'g'),
    lower(trim(employee_name)),
    work_date,
    submitted_at desc
  );

create table if not exists public.task_admin_events (
  id bigint generated by default as identity primary key,
  event_key text unique,
  event_type text not null check (event_type in ('assignment', 'recurring', 'planner_task', 'planner_consumed', 'cliq_webhook')),
  changed_at timestamptz not null default now(),
  work_date date,
  department text not null,
  employee_name text not null,
  task_id text,
  title text,
  status text,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

do $$
begin
  if exists (
    select 1
    from pg_constraint c
    where c.conname = 'task_admin_events_event_type_check'
      and c.conrelid = 'public.task_admin_events'::regclass
  ) then
    alter table public.task_admin_events drop constraint task_admin_events_event_type_check;
  end if;
  alter table public.task_admin_events
    add constraint task_admin_events_event_type_check
    check (event_type in ('assignment', 'recurring', 'planner_task', 'planner_consumed', 'cliq_webhook'));
exception
  when duplicate_object then null;
end $$;

create index if not exists idx_task_admin_events_lookup
  on public.task_admin_events (event_type, department, employee_name, work_date, changed_at);

create index if not exists idx_task_admin_events_type_date
  on public.task_admin_events (event_type, work_date, changed_at desc);

create index if not exists idx_task_admin_events_canonical_lookup
  on public.task_admin_events (
    event_type,
    regexp_replace(lower(coalesce(department, '')), '[^a-z]', '', 'g'),
    lower(trim(employee_name)),
    work_date,
    changed_at desc
  );

create index if not exists idx_users_directory_active_canonical
  on public.users_directory (active, regexp_replace(lower(coalesce(department, '')), '[^a-z]', '', 'g'), lower(trim(employee_name)));

create table if not exists public.user_streaks (
  id bigint generated by default as identity primary key,
  department text not null,
  employee_name text not null,
  current_streak integer not null default 0,
  best_streak integer not null default 0,
  last_counted_date date,
  updated_at timestamptz not null default now(),
  unique (department, employee_name)
);

create index if not exists idx_user_streaks_lookup
  on public.user_streaks (department, employee_name);

create table if not exists public.leave_days (
  id bigint generated by default as identity primary key,
  leave_date date not null,
  department text not null,
  employee_name text not null,
  leave_status text not null default 'Leave',
  reason text default '',
  marked_by text default '',
  source text default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (leave_date, department, employee_name)
);

alter table public.leave_days add column if not exists leave_status text not null default 'Leave';
alter table public.leave_days add column if not exists reason text default '';
alter table public.leave_days add column if not exists marked_by text default '';
alter table public.leave_days add column if not exists source text default 'manual';
alter table public.leave_days add column if not exists created_at timestamptz not null default now();
alter table public.leave_days add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_leave_days_lookup
  on public.leave_days (leave_date, department, employee_name, leave_status);

-- ============================================================================
-- Security model (RPC-first)
-- ============================================================================

alter table public.users_directory enable row level security;
alter table public.admins_directory enable row level security;
alter table public.task_submissions enable row level security;
alter table public.task_admin_events enable row level security;
alter table public.user_streaks enable row level security;
alter table public.leave_days enable row level security;

-- No direct table policies for anon/authenticated.
-- Access should go through SECURITY DEFINER RPC functions.

-- ============================================================================
-- Helpers
-- ============================================================================

create or replace function public.hash_secret(p_secret text)
returns text
language sql
immutable
as $$
  select md5(coalesce(p_secret, ''));
$$;

create or replace function public.secret_matches(p_secret text, p_hash text)
returns boolean
language sql
stable
as $$
  select md5(coalesce(p_secret, '')) = coalesce(p_hash, '');
$$;

create or replace function public.canonical_department_key(p_val text)
returns text
language sql
immutable
as $$
  select
    case regexp_replace(lower(coalesce(p_val, '')), '[^a-z]', '', 'g')
      when 'hr' then 'humanresources'
      when 'humanresources' then 'humanresources'
      when 'it' then 'informationtechnology'
      when 'informationtechnology' then 'informationtechnology'
      when 'op' then 'operations'
      when 'operations' then 'operations'
      when 'rs' then 'research'
      when 'research' then 'research'
      when 'eq' then 'equity'
      when 'equity' then 'equity'
      when 'dr' then 'directreportees'
      when 'directreportees' then 'directreportees'
      when 'mk' then 'marketing'
      when 'marketing' then 'marketing'
      else regexp_replace(lower(coalesce(p_val, '')), '[^a-z]', '', 'g')
    end;
$$;

create or replace function public.normalize_priority(p_val text)
returns text
language sql
immutable
as $$
  select case lower(coalesce(trim(p_val), ''))
    when 'high' then 'High'
    when 'low' then 'Low'
    else 'Medium'
  end;
$$;

create or replace function public.to_date_safe(p_val text)
returns date
language plpgsql
immutable
as $$
declare
  d date;
begin
  begin
    d := p_val::date;
  exception when others then
    d := null;
  end;
  return d;
end;
$$;

create or replace function public.rfc3339_now()
returns text
language sql
stable
as $$
  select to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"');
$$;

create or replace function public.event_digest_key(p_event_type text, p_payload jsonb)
returns text
language sql
immutable
as $$
  select 'adm-' || md5(coalesce(p_event_type, '') || '|' || coalesce(p_payload::text, ''));
$$;

create or replace function public.last_day_of_month(p_work_date date)
returns int
language sql
immutable
as $$
  select extract(day from (date_trunc('month', p_work_date) + interval '1 month - 1 day'))::int;
$$;

create or replace function public.min_people_for_org_workday()
returns int
language sql
immutable
as $$
  select 3;
$$;

create or replace function public.is_non_working_calendar_day(p_date date)
returns boolean
language sql
immutable
as $$
  select
    p_date is null
    or extract(dow from p_date)::int = 0
    or p_date = any(array[
      date '2026-01-10', date '2026-01-24', date '2026-01-25', date '2026-01-26',
      date '2026-02-07', date '2026-02-21',
      date '2026-03-03', date '2026-03-07', date '2026-03-21',
      date '2026-04-03', date '2026-04-04', date '2026-04-05', date '2026-04-18',
      date '2026-05-01', date '2026-05-02', date '2026-05-03', date '2026-05-16', date '2026-05-23',
      date '2026-06-13', date '2026-06-26', date '2026-06-27', date '2026-06-28',
      date '2026-07-11', date '2026-07-18', date '2026-07-25',
      date '2026-08-01', date '2026-08-15', date '2026-08-29',
      date '2026-09-12', date '2026-09-13', date '2026-09-14', date '2026-09-26',
      date '2026-10-02', date '2026-10-03', date '2026-10-04', date '2026-10-10', date '2026-10-17', date '2026-10-20',
      date '2026-11-07', date '2026-11-08', date '2026-11-09', date '2026-11-10', date '2026-11-28',
      date '2026-12-12', date '2026-12-25', date '2026-12-26', date '2026-12-27'
    ]);
$$;

create or replace function public.is_org_working_day(
  p_date date,
  p_department text default null
)
returns boolean
language plpgsql
stable
as $$
declare
  v_people_count int := 0;
begin
  if public.is_non_working_calendar_day(p_date) then
    return false;
  end if;

  select count(distinct lower(trim(s.employee_name)))::int
  into v_people_count
  from public.task_submissions s
  where s.work_date = p_date
    and s.stage in ('SOD', 'EOD');

  return v_people_count >= public.min_people_for_org_workday();
end;
$$;

create or replace function public.count_working_days_excluding_sunday_and_leave(
  p_from date,
  p_to date,
  p_department text default null,
  p_employee_name text default null
)
returns int
language plpgsql
stable
as $$
declare
  d date;
  v_count int := 0;
  v_leave_table_exists boolean := to_regclass('public.leave_days') is not null;
  v_is_leave boolean;
begin
  if p_from is null or p_to is null or p_to < p_from then
    return 0;
  end if;

  d := p_from;
  while d <= p_to loop
    if not public.is_non_working_calendar_day(d) and public.is_org_working_day(d, p_department) then
      if v_leave_table_exists then
        execute
          'select exists (
             select 1
             from public.leave_days l
             where l.leave_date = $1
               and ($2 is null or public.canonical_department_key(l.department) = public.canonical_department_key($2))
               and ($3 is null or lower(trim(l.employee_name)) = lower(trim($3)))
               and upper(coalesce(l.leave_status, ''LEAVE'')) = ''LEAVE''
           )'
          into v_is_leave
          using d, p_department, p_employee_name;
        if not coalesce(v_is_leave, false) then
          v_count := v_count + 1;
        end if;
      else
        v_count := v_count + 1;
      end if;
    end if;
    d := d + 1;
  end loop;
  return v_count;
end;
$$;

create or replace function public.is_working_day_for_user(
  p_date date,
  p_department text default null,
  p_employee_name text default null
)
returns boolean
language plpgsql
stable
as $$
declare
  v_leave_table_exists boolean := to_regclass('public.leave_days') is not null;
  v_is_leave boolean := false;
begin
  if p_date is null then
    return false;
  end if;
  if public.is_non_working_calendar_day(p_date) then
    return false;
  end if;
  if not public.is_org_working_day(p_date, p_department) then
    return false;
  end if;
  if v_leave_table_exists then
    select exists (
      select 1
      from public.leave_days l
      where l.leave_date = p_date
        and (p_department is null or public.canonical_department_key(l.department) = public.canonical_department_key(p_department))
        and (p_employee_name is null or lower(trim(l.employee_name)) = lower(trim(p_employee_name)))
        and upper(coalesce(l.leave_status, 'LEAVE')) = 'LEAVE'
    ) into v_is_leave;
  end if;
  return not v_is_leave;
end;
$$;

create or replace function public.previous_working_day_for_user(
  p_date date,
  p_department text default null,
  p_employee_name text default null
)
returns date
language plpgsql
stable
as $$
declare
  d date := p_date - 1;
begin
  while d >= (p_date - 370) loop
    if public.is_working_day_for_user(d, p_department, p_employee_name) then
      return d;
    end if;
    d := d - 1;
  end loop;
  return null;
end;
$$;

create or replace function public.compute_user_streak_from_submissions(
  p_department text,
  p_employee_name text
)
returns table(
  current_streak int,
  best_streak int,
  last_counted_date date
)
language plpgsql
stable
as $$
declare
  d date;
  v_prev_working_day date;
  v_cur int := 0;
  v_best int := 0;
  v_last date := null;
  v_today_ist date := (now() at time zone 'Asia/Kolkata')::date;
  v_broken_after_last boolean := false;
begin
  for d in
    with day_flags as (
      select
        s.work_date,
        bool_or(s.stage = 'SOD') as has_sod,
        bool_or(s.stage = 'EOD') as has_eod
      from public.task_submissions s
      where public.canonical_department_key(s.department) = public.canonical_department_key(p_department)
        and lower(trim(s.employee_name)) = lower(trim(p_employee_name))
      group by s.work_date
    )
    select f.work_date
    from day_flags f
    where f.has_sod = true
      and f.has_eod = true
      and public.is_working_day_for_user(f.work_date, p_department, p_employee_name)
    order by f.work_date
  loop
    if v_last is null then
      v_cur := 1;
    else
      v_prev_working_day := public.previous_working_day_for_user(d, p_department, p_employee_name);
      if v_prev_working_day is not null and v_last = v_prev_working_day then
        v_cur := v_cur + 1;
      else
        v_cur := 1;
      end if;
    end if;
    v_best := greatest(v_best, v_cur);
    v_last := d;
  end loop;

  if v_last is not null and v_last < (v_today_ist - 0) then
    with day_flags as (
      select
        s.work_date,
        bool_or(s.stage = 'SOD') as has_sod,
        bool_or(s.stage = 'EOD') as has_eod
      from public.task_submissions s
      where public.canonical_department_key(s.department) = public.canonical_department_key(p_department)
        and lower(trim(s.employee_name)) = lower(trim(p_employee_name))
      group by s.work_date
    ),
    day_seq as (
      select g::date as work_date
      from generate_series(v_last + 1, v_today_ist - 1, interval '1 day') g
    )
    select exists(
      select 1
      from day_seq d2
      left join day_flags f on f.work_date = d2.work_date
      where public.is_working_day_for_user(d2.work_date, p_department, p_employee_name)
        and not (coalesce(f.has_sod, false) and coalesce(f.has_eod, false))
    )
    into v_broken_after_last;

    if v_broken_after_last then
      v_cur := 0;
    end if;
  end if;

  return query
  select v_cur, v_best, v_last;
end;
$$;

-- ============================================================================
-- Access RPCs
-- ============================================================================

create or replace function public.rpc_validate_user_access(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_department text := coalesce(p_payload->>'dept', p_payload->>'department', '');
  v_employee text := coalesce(p_payload->>'name', p_payload->>'employeeName', '');
  v_code text := coalesce(p_payload->>'code', p_payload->>'accessCode', '');
  rec record;
begin
  select * into rec
  from public.users_directory u
  where public.canonical_department_key(u.department) = public.canonical_department_key(v_department)
    and lower(trim(u.employee_name)) = lower(trim(v_employee))
    and u.active = true
  limit 1;

  if rec is null then
    return jsonb_build_object('ok', false, 'message', 'Invalid access.');
  end if;

  if not public.secret_matches(v_code, rec.access_code_hash) then
    return jsonb_build_object('ok', false, 'message', 'Invalid access.');
  end if;

  return jsonb_build_object('ok', true, 'dept', rec.department, 'name', rec.employee_name);
end;
$$;

create or replace function public.rpc_validate_admin_access(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin text := coalesce(p_payload->>'admin', '');
  v_code text := coalesce(p_payload->>'code', '');
  rec record;
begin
  select * into rec
  from public.admins_directory a
  where lower(trim(a.admin_name)) = lower(trim(v_admin))
    and a.active = true
  limit 1;

  if rec is null then
    return jsonb_build_object('ok', false, 'message', 'Admin not found.');
  end if;
  if not public.secret_matches(v_code, rec.admin_code_hash) then
    return jsonb_build_object('ok', false, 'message', 'Invalid admin code.');
  end if;

  return jsonb_build_object(
    'ok', true,
    'admin', rec.admin_name,
    'role', rec.role,
    'allowedDepartments', rec.allowed_departments_json
  );
end;
$$;

-- ============================================================================
-- Submission RPCs
-- ============================================================================

create or replace function public.rpc_submit_sod(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_work_date date := coalesce(public.to_date_safe(p_payload->>'workDate'), current_date);
  v_task_count int := coalesce(jsonb_array_length(coalesce(p_payload->'tasks', '[]'::jsonb)), 0);
begin
  insert into public.task_submissions (
    request_id, stage, submitted_at, work_date, department, employee_name, access_code, task_count, total_spent_minutes, payload_json
  ) values (
    nullif(p_payload->>'requestId',''),
    'SOD',
    coalesce((p_payload->>'submittedAt')::timestamptz, now()),
    v_work_date,
    coalesce(p_payload->>'department',''),
    coalesce(p_payload->>'employeeName',''),
    coalesce(p_payload->>'accessCode', p_payload->>'code', ''),
    v_task_count,
    0,
    p_payload
  ) on conflict (request_id) do nothing;

  return jsonb_build_object('ok', true, 'taskCount', v_task_count);
end;
$$;

create or replace function public.rpc_submit_eod(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_work_date date := coalesce(public.to_date_safe(p_payload->>'workDate'), current_date);
  v_task_count int := coalesce(jsonb_array_length(coalesce(p_payload->'updates', '[]'::jsonb)), 0);
  v_total_minutes int := coalesce(nullif(p_payload->>'totalSpentMinutes','')::int, 0);
  v_department text := coalesce(p_payload->>'department','');
  v_employee text := coalesce(p_payload->>'employeeName','');
  v_hist record;
  v_prev_current int := 0;
  v_prev_best int := 0;
  v_next_current int := 0;
  v_next_best int := 0;
  v_incremented boolean := false;
  v_milestone int := null;
begin
  insert into public.task_submissions (
    request_id, stage, submitted_at, work_date, department, employee_name, access_code, task_count, total_spent_minutes, payload_json
  ) values (
    nullif(p_payload->>'requestId',''),
    'EOD',
    coalesce((p_payload->>'submittedAt')::timestamptz, now()),
    v_work_date,
    v_department,
    v_employee,
    coalesce(p_payload->>'accessCode', p_payload->>'code', ''),
    v_task_count,
    v_total_minutes,
    p_payload
  ) on conflict (request_id) do nothing;

  select
    coalesce(us.current_streak, 0),
    coalesce(us.best_streak, 0)
  into v_prev_current, v_prev_best
  from public.user_streaks us
  where public.canonical_department_key(us.department) = public.canonical_department_key(v_department)
    and lower(trim(us.employee_name)) = lower(trim(v_employee))
  limit 1;

  select *
  into v_hist
  from public.compute_user_streak_from_submissions(v_department, v_employee);
  v_next_current := coalesce(v_hist.current_streak, 0);
  v_next_best := greatest(v_next_current, coalesce(v_hist.best_streak, 0), coalesce(v_prev_best, 0));
  v_incremented := v_next_current > coalesce(v_prev_current, 0);

  insert into public.user_streaks (department, employee_name, current_streak, best_streak, last_counted_date, updated_at)
  values (
    v_department,
    v_employee,
    v_next_current,
    v_next_best,
    v_hist.last_counted_date,
    now()
  )
  on conflict (department, employee_name) do update
  set current_streak = excluded.current_streak,
      best_streak = greatest(public.user_streaks.best_streak, excluded.best_streak),
      last_counted_date = excluded.last_counted_date,
      updated_at = now();

  if v_incremented and v_next_current in (7, 30, 100, 365) then
    v_milestone := v_next_current;
  end if;

  return jsonb_build_object(
    'ok', true,
    'taskCount', v_task_count,
    'totalSpentMinutes', v_total_minutes,
    'streak', jsonb_build_object(
      'current', coalesce(v_next_current, 0),
      'best', coalesce(v_next_best, 0),
      'incremented', v_incremented,
      'milestone', v_milestone,
      'countedDate', v_work_date::text
    )
  );
end;
$$;

create or replace function public.rpc_get_user_streak(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_department text := coalesce(p_payload->>'department', p_payload->>'dept', '');
  v_employee text := coalesce(p_payload->>'employeeName', p_payload->>'name', '');
  v_code text := coalesce(p_payload->>'accessCode', p_payload->>'code', '');
  v_hist record;
  v_sod_count int := 0;
  v_eod_count int := 0;
  v_today_ist date := (now() at time zone 'Asia/Kolkata')::date;
  v_start_date date;
  v_broken_since date := null;
  v_missing_sod boolean := false;
  v_missing_eod boolean := false;
  v_is_broken boolean := false;
  v_reason text := '';
begin
  perform 1
  from public.users_directory u
  where public.canonical_department_key(u.department) = public.canonical_department_key(v_department)
    and lower(trim(u.employee_name)) = lower(trim(v_employee))
    and u.active = true
    and public.secret_matches(v_code, u.access_code_hash)
  limit 1;
  if not found then
    return jsonb_build_object('ok', false, 'message', 'Invalid access.');
  end if;

  select *
  into v_hist
  from public.compute_user_streak_from_submissions(v_department, v_employee);

  insert into public.user_streaks (department, employee_name, current_streak, best_streak, last_counted_date, updated_at)
  values (
    v_department,
    v_employee,
    coalesce(v_hist.current_streak, 0),
    coalesce(v_hist.best_streak, 0),
    v_hist.last_counted_date,
    now()
  )
  on conflict (department, employee_name) do update
  set current_streak = excluded.current_streak,
      best_streak = greatest(public.user_streaks.best_streak, excluded.best_streak),
      last_counted_date = excluded.last_counted_date,
      updated_at = now();

  select count(distinct s.work_date)::int
  into v_sod_count
  from public.task_submissions s
  where s.stage = 'SOD'
    and public.canonical_department_key(s.department) = public.canonical_department_key(v_department)
    and lower(trim(s.employee_name)) = lower(trim(v_employee));

  select count(distinct s.work_date)::int
  into v_eod_count
  from public.task_submissions s
  where s.stage = 'EOD'
    and public.canonical_department_key(s.department) = public.canonical_department_key(v_department)
    and lower(trim(s.employee_name)) = lower(trim(v_employee));

  v_start_date := coalesce(v_hist.last_counted_date + 1, null);
  if v_start_date is not null and v_start_date <= (v_today_ist - 1) then
    with day_flags as (
      select
        s.work_date,
        bool_or(s.stage = 'SOD') as has_sod,
        bool_or(s.stage = 'EOD') as has_eod
      from public.task_submissions s
      where public.canonical_department_key(s.department) = public.canonical_department_key(v_department)
        and lower(trim(s.employee_name)) = lower(trim(v_employee))
      group by s.work_date
    ),
    day_seq as (
      select g::date as work_date
      from generate_series(v_start_date, v_today_ist - 1, interval '1 day') g
    )
    select
      d.work_date,
      not coalesce(f.has_sod, false) as miss_sod,
      not coalesce(f.has_eod, false) as miss_eod
    into v_broken_since, v_missing_sod, v_missing_eod
    from day_seq d
    left join day_flags f on f.work_date = d.work_date
    where public.is_working_day_for_user(d.work_date, v_department, v_employee)
      and not (coalesce(f.has_sod, false) and coalesce(f.has_eod, false))
    order by d.work_date
    limit 1;
  end if;

  v_is_broken := v_broken_since is not null;
  if v_is_broken then
    if v_missing_sod and v_missing_eod then
      v_reason := 'SOD and EOD were not submitted';
    elsif v_missing_sod then
      v_reason := 'SOD was not submitted';
    else
      v_reason := 'EOD was not submitted';
    end if;
  end if;

  return jsonb_build_object(
    'ok', true,
    'current', coalesce(v_hist.current_streak, 0),
    'best', coalesce(v_hist.best_streak, 0),
    'lastCountedDate', case when v_hist.last_counted_date is null then null else v_hist.last_counted_date::text end,
    'sodSubmittedDays', coalesce(v_sod_count, 0),
    'eodSubmittedDays', coalesce(v_eod_count, 0),
    'isBroken', v_is_broken,
    'brokenSinceDate', case when v_broken_since is null then null else v_broken_since::text end,
    'brokenReason', case when v_is_broken then v_reason else null end
  );
end;
$$;

create or replace function public.rpc_set_user_day_status(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_department text := coalesce(p_payload->>'department', p_payload->>'dept', '');
  v_employee text := coalesce(p_payload->>'employeeName', p_payload->>'name', '');
  v_code text := coalesce(p_payload->>'accessCode', p_payload->>'code', '');
  v_work_date date := coalesce(public.to_date_safe(p_payload->>'workDate'), (now() at time zone 'Asia/Kolkata')::date);
  v_status text := upper(trim(coalesce(p_payload->>'status', '')));
  v_reason text := coalesce(p_payload->>'reason', '');
  v_marked_by text := coalesce(p_payload->>'markedBy', v_employee);
  v_hist record;
begin
  perform 1
  from public.users_directory u
  where public.canonical_department_key(u.department) = public.canonical_department_key(v_department)
    and lower(trim(u.employee_name)) = lower(trim(v_employee))
    and u.active = true
    and public.secret_matches(v_code, u.access_code_hash)
  limit 1;
  if not found then
    return jsonb_build_object('ok', false, 'message', 'Invalid access.');
  end if;

  if v_status not in ('LEAVE', 'ABSENT', 'CLEAR') then
    return jsonb_build_object('ok', false, 'message', 'Invalid status. Use Leave, Absent, or Clear.');
  end if;

  if v_status = 'CLEAR' then
    delete from public.leave_days l
    where l.leave_date = v_work_date
      and public.canonical_department_key(l.department) = public.canonical_department_key(v_department)
      and lower(trim(l.employee_name)) = lower(trim(v_employee));
  else
    insert into public.leave_days (
      leave_date, department, employee_name, leave_status, reason, marked_by, source, updated_at
    ) values (
      v_work_date, v_department, v_employee,
      case when v_status = 'LEAVE' then 'Leave' else 'Absent' end,
      v_reason, v_marked_by, 'rpc_set_user_day_status', now()
    )
    on conflict (leave_date, department, employee_name) do update
    set leave_status = excluded.leave_status,
        reason = excluded.reason,
        marked_by = excluded.marked_by,
        source = excluded.source,
        updated_at = now();
  end if;

  select *
  into v_hist
  from public.compute_user_streak_from_submissions(v_department, v_employee);

  insert into public.user_streaks (department, employee_name, current_streak, best_streak, last_counted_date, updated_at)
  values (
    v_department,
    v_employee,
    coalesce(v_hist.current_streak, 0),
    coalesce(v_hist.best_streak, 0),
    v_hist.last_counted_date,
    now()
  )
  on conflict (department, employee_name) do update
  set current_streak = excluded.current_streak,
      best_streak = greatest(public.user_streaks.best_streak, excluded.best_streak),
      last_counted_date = excluded.last_counted_date,
      updated_at = now();

  return jsonb_build_object(
    'ok', true,
    'workDate', v_work_date::text,
    'status', case when v_status = 'CLEAR' then null else (case when v_status = 'LEAVE' then 'Leave' else 'Absent' end) end,
    'streak', jsonb_build_object(
      'current', coalesce(v_hist.current_streak, 0),
      'best', coalesce(v_hist.best_streak, 0),
      'lastCountedDate', case when v_hist.last_counted_date is null then null else v_hist.last_counted_date::text end
    )
  );
end;
$$;

create or replace function public.rpc_get_streak_leaderboard(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin text := coalesce(p_payload->>'admin', '');
  v_admin_code text := coalesce(p_payload->>'code', '');
  v_department text := coalesce(p_payload->>'department', '');
  v_user_dept text := coalesce(p_payload->>'dept', p_payload->>'department', '');
  v_user_name text := coalesce(p_payload->>'name', p_payload->>'employeeName', '');
  v_user_code text := coalesce(p_payload->>'accessCode', p_payload->>'code', '');
  v_limit int := greatest(1, least(coalesce(nullif(p_payload->>'limit', '')::int, 3), 20));
  v_allowed boolean := false;
  v_dep_filter text := nullif(trim(v_department), '');
  v_payload jsonb;
begin
  if nullif(trim(v_admin), '') is not null then
    perform 1
    from public.admins_directory a
    where lower(trim(a.admin_name)) = lower(trim(v_admin))
      and a.active = true
      and public.secret_matches(v_admin_code, a.admin_code_hash)
    limit 1;
    v_allowed := found;
  else
    perform 1
    from public.users_directory u
    where public.canonical_department_key(u.department) = public.canonical_department_key(v_user_dept)
      and lower(trim(u.employee_name)) = lower(trim(v_user_name))
      and u.active = true
      and public.secret_matches(v_user_code, u.access_code_hash)
    limit 1;
    v_allowed := found;
  end if;

  if not v_allowed then
    return jsonb_build_object('ok', false, 'message', 'Invalid access.');
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'rank', t.rn,
        'employeeName', t.employee_name,
        'department', t.department,
        'current', t.current_streak,
        'best', t.best_streak
      )
      order by t.rn
    ),
    '[]'::jsonb
  )
  into v_payload
  from (
    select
      row_number() over (
        order by
          coalesce(hist.current_streak, 0) desc,
          coalesce(hist.best_streak, 0) desc,
          coalesce(hist.last_counted_date, date '1900-01-01') desc,
          ud.employee_name asc
      ) as rn,
      ud.employee_name,
      ud.department,
      coalesce(hist.current_streak, 0) as current_streak,
      coalesce(hist.best_streak, 0) as best_streak
    from public.users_directory ud
    left join lateral public.compute_user_streak_from_submissions(ud.department, ud.employee_name) hist
      on true
    where ud.active = true
      and public.canonical_department_key(ud.department) <> 'directreportees'
      and (v_dep_filter is null or lower(v_dep_filter) = 'all' or public.canonical_department_key(ud.department) = public.canonical_department_key(v_dep_filter))
    order by
      coalesce(hist.current_streak, 0) desc,
      coalesce(hist.best_streak, 0) desc,
      coalesce(hist.last_counted_date, date '1900-01-01') desc,
      ud.employee_name asc
    limit v_limit
  ) t;

  return jsonb_build_object(
    'ok', true,
    'leaders', coalesce(v_payload, '[]'::jsonb)
  );
end;
$$;

create or replace function public.rpc_get_submitted_day_details(p_payload jsonb)
returns jsonb
language sql
security definer
set search_path = public
as $$
with req as (
  select
    coalesce(p_payload->>'department','') as department,
    public.canonical_department_key(coalesce(p_payload->>'department','')) as dep_key,
    coalesce(p_payload->>'employeeName','') as employee_name,
    coalesce(public.to_date_safe(p_payload->>'workDate'), current_date) as work_date
),
sod as (
  select s.*
  from public.task_submissions s
  join req r on public.canonical_department_key(s.department) = r.dep_key and r.employee_name = s.employee_name and r.work_date = s.work_date
  where s.stage = 'SOD'
  order by s.submitted_at desc
  limit 1
),
eod as (
  select s.*
  from public.task_submissions s
  join req r on public.canonical_department_key(s.department) = r.dep_key and r.employee_name = s.employee_name and r.work_date = s.work_date
  where s.stage = 'EOD'
  order by s.submitted_at desc
  limit 1
)
select jsonb_build_object(
  'ok', true,
  'workDate', (select work_date::text from req),
  'hasSod', exists(select 1 from sod),
  'hasEod', exists(select 1 from eod),
  'sodTasks', coalesce((select coalesce(payload_json->'tasks', payload_json->'updates', '[]'::jsonb) from sod), '[]'::jsonb),
  'eodUpdates', coalesce((select coalesce(payload_json->'updates', payload_json->'tasks', payload_json->'completedTasks', '[]'::jsonb) from eod), '[]'::jsonb)
);
$$;

-- ============================================================================
-- Carryover / assignments / recurring
-- ============================================================================

create or replace function public.rpc_get_carryover(p_payload jsonb)
returns jsonb
language sql
security definer
set search_path = public
as $$
with req as (
  select
    coalesce(p_payload->>'department','') as department,
    public.canonical_department_key(coalesce(p_payload->>'department','')) as dep_key,
    coalesce(p_payload->>'employeeName','') as employee_name,
    coalesce(public.to_date_safe(p_payload->>'workDate'), current_date) as work_date
),
eod_latest_per_day as (
  select distinct on (s.work_date)
    s.work_date,
    s.submitted_at,
    s.payload_json
  from public.task_submissions s
  join req r on public.canonical_department_key(s.department) = r.dep_key and r.employee_name = s.employee_name
  where s.stage = 'EOD'
    and s.work_date < r.work_date
  order by s.work_date, s.submitted_at desc
),
eod_updates as (
  select
    d.work_date,
    d.submitted_at,
    row_number() over (
      partition by d.work_date, d.submitted_at
      order by coalesce(u->>'taskId', lower(coalesce(u->>'title','')))
    ) as row_ord,
    coalesce(u->>'taskId', '') as task_id,
    coalesce(u->>'title', '') as title,
    coalesce(nullif(u->>'taskId',''), lower(coalesce(u->>'title',''))) as task_key,
    public.normalize_priority(coalesce(u->>'priority','Medium')) as priority,
    coalesce(
      nullif(u->>'completionPercent','')::int,
      nullif(u->>'completion','')::int,
      nullif(u->>'progress','')::int,
      0
    )::int as completion,
    coalesce(u->>'note','') as note
  from eod_latest_per_day d,
  lateral jsonb_array_elements(coalesce(d.payload_json->'updates', '[]'::jsonb)) u
  where coalesce(u->>'title','') <> ''
),
ordered_updates as (
  select
    x.*,
    sum(case when x.completion >= 100 then 1 else 0 end) over (
      partition by x.task_key
      order by x.work_date, x.submitted_at, x.row_ord
      rows between unbounded preceding and current row
    ) as reset_count,
    row_number() over (
      partition by x.task_key
      order by x.work_date desc, x.submitted_at desc, x.row_ord desc
    ) as latest_rn
  from eod_updates x
),
low_groups as (
  select
    task_key,
    reset_count,
    min(work_date) as carry_start_date
  from ordered_updates
  where completion < 100
  group by task_key, reset_count
),
open_rows as (
  select
    o.task_key,
    o.task_id,
    o.title,
    o.priority,
    o.completion,
    o.note,
    l.carry_start_date,
    o.work_date as last_work_date
  from ordered_updates o
  join low_groups l
    on l.task_key = o.task_key
   and l.reset_count = o.reset_count
  where o.latest_rn = 1
    and o.completion < 100
)
select jsonb_build_object(
  'ok', true,
  'tasks', coalesce(jsonb_agg(jsonb_build_object(
    'taskId', coalesce(
      nullif(task_id,''),
      'co-' || md5(coalesce(task_key,'') || '|' || coalesce(carry_start_date::text,'') || '|' || coalesce(title,''))
    ),
    'title', title,
    'priority', priority,
    'addedDate', carry_start_date::text,
    'lastCompletion', completion,
    'lastNote', note
  ) order by last_work_date desc, title) filter (where title <> ''), '[]'::jsonb),
  'sourceWorkDate', coalesce((select max(work_date)::text from eod_latest_per_day), '')
)
from open_rows;
$$;

create or replace function public.rpc_get_assignments(p_payload jsonb)
returns jsonb
language sql
security definer
set search_path = public
as $$
with req as (
  select
    coalesce(p_payload->>'department','') as department,
    public.canonical_department_key(coalesce(p_payload->>'department','')) as dep_key,
    coalesce(p_payload->>'employeeName','') as employee_name,
    coalesce(public.to_date_safe(p_payload->>'workDate'), current_date) as work_date
),
assignment_latest as (
  select distinct on (coalesce(nullif(e.task_id, ''), nullif(e.payload_json->>'taskId', ''), lower(trim(coalesce(e.title, '')))))
    coalesce(nullif(e.task_id, ''), nullif(e.payload_json->>'taskId', ''), '') as task_id,
    coalesce(e.title, '') as title,
    public.normalize_priority(coalesce(e.payload_json->>'priority', 'Medium')) as priority,
    coalesce(e.payload_json->>'assignedBy', '') as assigned_by,
    coalesce(e.payload_json->>'assignedAt', '') as assigned_at,
    coalesce(nullif(e.payload_json->>'deadlineDays', '')::int, 1) as deadline_days,
    coalesce(e.payload_json->>'deadlineDate', '') as deadline_date,
    coalesce(e.payload_json->>'status', e.status, 'Assigned') as status
  from public.task_admin_events e
  join req r on public.canonical_department_key(e.department) = r.dep_key and e.employee_name = r.employee_name
  where e.event_type = 'assignment'
    and coalesce(e.work_date, r.work_date) <= r.work_date
  order by coalesce(nullif(e.task_id, ''), nullif(e.payload_json->>'taskId', ''), lower(trim(coalesce(e.title, '')))), e.changed_at desc
),
completed_assigned as (
  select distinct
    nullif(u->>'taskId', '') as task_id,
    lower(trim(coalesce(u->>'title', ''))) as title_key
  from public.task_submissions s
  join req r
    on public.canonical_department_key(s.department) = r.dep_key
   and s.employee_name = r.employee_name
   and s.stage = 'EOD'
   and s.work_date <= r.work_date
  cross join lateral (
    select value as u
    from jsonb_array_elements(coalesce(s.payload_json->'updates', '[]'::jsonb))
    union all
    select value as u
    from jsonb_array_elements(coalesce(s.payload_json->'completedTasks', '[]'::jsonb))
  ) src
  where coalesce(nullif(u->>'taskId', ''), lower(trim(coalesce(u->>'title', ''))), '') <> ''
    and coalesce(nullif(u->>'completionPercent', '')::int, nullif(u->>'completion', '')::int, 0) >= 100
),
eod_assigned_updates as (
  select
    s.work_date,
    s.submitted_at,
    nullif(u->>'taskId', '') as task_id,
    lower(trim(coalesce(u->>'title', ''))) as title_key,
    coalesce(nullif(u->>'completionPercent', '')::int, nullif(u->>'completion', '')::int, 0) as completion_percent,
    coalesce(u->>'note', '') as note
  from public.task_submissions s
  join req r
    on public.canonical_department_key(s.department) = r.dep_key
   and s.employee_name = r.employee_name
   and s.stage = 'EOD'
   and s.work_date <= r.work_date
  cross join lateral (
    select value as u
    from jsonb_array_elements(coalesce(s.payload_json->'updates', '[]'::jsonb))
    union all
    select value as u
    from jsonb_array_elements(coalesce(s.payload_json->'completedTasks', '[]'::jsonb))
  ) src
  where coalesce(nullif(src.u->>'taskId', ''), lower(trim(coalesce(src.u->>'title', ''))), '') <> ''
),
latest_assigned_progress as (
  select distinct on (coalesce(task_id, title_key))
    coalesce(task_id, title_key) as progress_key,
    completion_percent,
    note
  from eod_assigned_updates
  where coalesce(task_id, title_key) is not null
  order by coalesce(task_id, title_key), work_date desc, submitted_at desc
),
tasks as (
  select jsonb_build_object(
    'taskId', coalesce(
      nullif(a.task_id, ''),
      'asg-' || md5(lower(coalesce(a.title, '')) || '|' || coalesce(a.assigned_at, '') || '|' || coalesce(a.deadline_date, ''))
    ),
    'title', a.title,
    'priority', a.priority,
    'assignedBy', a.assigned_by,
    'assignedAt', a.assigned_at,
    'deadlineDays', a.deadline_days,
    'deadlineDate', a.deadline_date,
    'lastCompletion', coalesce(lp.completion_percent, 0),
    'lastNote', coalesce(lp.note, ''),
    'source', 'admin-assigned'
  ) as t
  from assignment_latest a
  left join latest_assigned_progress lp
    on lp.progress_key = coalesce(nullif(a.task_id, ''), lower(trim(coalesce(a.title, ''))))
  where lower(coalesce(a.status, 'assigned')) = 'assigned'
    and not exists (
      select 1
      from completed_assigned c
      where (
        c.task_id is not null
        and nullif(a.task_id, '') is not null
        and c.task_id = nullif(a.task_id, '')
      )
      or (
        c.title_key <> ''
        and c.title_key = lower(trim(coalesce(a.title, '')))
      )
    )
)
select jsonb_build_object(
  'ok', true,
  'tasks', coalesce(jsonb_agg(t) filter (where (t->>'title') <> ''), '[]'::jsonb),
  'sourceWorkDate', (select work_date::text from req)
) from tasks;
$$;

create or replace function public.rpc_get_recurring_tasks(p_payload jsonb)
returns jsonb
language sql
security definer
set search_path = public
as $$
with req as (
  select
    coalesce(p_payload->>'department','') as department,
    public.canonical_department_key(coalesce(p_payload->>'department','')) as dep_key,
    coalesce(p_payload->>'employeeName','') as employee_name,
    coalesce(public.to_date_safe(p_payload->>'workDate'), current_date) as work_date
),
ev as (
  select
    e.*,
    coalesce(e.payload_json->>'taskId', e.task_id, '') as task_id_k,
    coalesce(e.payload_json->>'title', e.title, '') as title_k
  from public.task_admin_events e
  join req r on r.dep_key = public.canonical_department_key(e.department) and r.employee_name = e.employee_name
  where e.event_type = 'recurring'
),
latest as (
  select distinct on (coalesce(nullif(task_id_k,''), lower(title_k)))
    coalesce(
      e.payload_json->>'taskId',
      e.task_id,
      'rec-' || md5(lower(coalesce(e.payload_json->>'title', e.title, '')) || '|' || coalesce(e.payload_json->>'startDate', ''))
    ) as task_id,
    coalesce(e.payload_json->>'title', e.title, '') as title,
    public.normalize_priority(coalesce(e.payload_json->>'priority', 'Medium')) as priority,
    coalesce(e.payload_json->>'frequency', 'Daily') as frequency,
    coalesce(public.to_date_safe(e.payload_json->>'startDate'), current_date) as start_date,
    nullif(e.payload_json->>'recurrenceWeekday','')::int as recurrence_weekday,
    nullif(e.payload_json->>'recurrenceDayOfMonth','')::int as recurrence_day_of_month,
    coalesce(e.payload_json->>'status', e.status, 'Active') as status,
    coalesce(nullif(e.payload_json->>'plannedHours','')::int, 0) as planned_hours,
    coalesce(nullif(e.payload_json->>'plannedMinutes','')::int, 0) as planned_minutes
  from ev e
  order by coalesce(nullif(task_id_k,''), lower(title_k)), e.changed_at desc
),
due as (
  select l.*
  from latest l, req r
  where lower(l.status) <> 'inactive'
    and r.work_date >= l.start_date
    and (
      lower(l.frequency) = 'daily'
      or (lower(l.frequency) = 'weekly' and extract(dow from r.work_date)::int = coalesce(l.recurrence_weekday, extract(dow from l.start_date)::int))
      or (lower(l.frequency) = 'monthly' and extract(day from r.work_date)::int = least(coalesce(l.recurrence_day_of_month, extract(day from l.start_date)::int), public.last_day_of_month(r.work_date)))
    )
)
select jsonb_build_object(
  'ok', true,
  'tasks', coalesce(jsonb_agg(jsonb_build_object(
    'taskId', task_id,
    'title', title,
    'priority', priority,
    'frequency', frequency,
    'startDate', start_date::text,
    'recurrenceWeekday', recurrence_weekday,
    'recurrenceDayOfMonth', recurrence_day_of_month,
    'plannedHours', planned_hours,
    'plannedMinutes', planned_minutes,
    'source', 'recurring',
    'lastCompletion', null,
    'lastNote', ''
  )) filter (where title <> ''), '[]'::jsonb),
  'sourceWorkDate', (select work_date::text from req)
) from due;
$$;

create or replace function public.rpc_sync_recurring_tasks(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  i jsonb;
  v_count int := 0;
  v_work_date date := coalesce(public.to_date_safe(p_payload->>'workDate'), current_date);
begin
  for i in select * from jsonb_array_elements(coalesce(p_payload->'tasks','[]'::jsonb))
  loop
    insert into public.task_admin_events(event_key,event_type,changed_at,work_date,department,employee_name,task_id,title,status,payload_json)
    values (
      public.event_digest_key('recurring', i || jsonb_build_object('changedAt', public.rfc3339_now())),
      'recurring',
      now(),
      v_work_date,
      coalesce(p_payload->>'department',''),
      coalesce(p_payload->>'employeeName',''),
      nullif(i->>'taskId',''),
      i->>'title',
      'Active',
      i || jsonb_build_object('status','Active','changedAt', public.rfc3339_now(), 'startDate', coalesce(i->>'startDate', v_work_date::text))
    ) on conflict (event_key) do nothing;
    v_count := v_count + 1;
  end loop;
  return jsonb_build_object('ok', true, 'upsertedCount', v_count, 'sourceWorkDate', v_work_date::text);
end;
$$;

create or replace function public.rpc_complete_recurring_tasks(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count int := 0;
  v_work_date date := coalesce(public.to_date_safe(p_payload->>'workDate'), current_date);
  t text;
begin
  for t in select jsonb_array_elements_text(coalesce(p_payload->'taskIds', '[]'::jsonb))
  loop
    insert into public.task_admin_events(event_key,event_type,changed_at,work_date,department,employee_name,task_id,title,status,payload_json)
    values (
      public.event_digest_key('recurring', jsonb_build_object('taskId', t, 'status', 'Inactive', 'workDate', v_work_date::text)),
      'recurring', now(), v_work_date,
      coalesce(p_payload->>'department',''),
      coalesce(p_payload->>'employeeName',''),
      t, '', 'Inactive',
      jsonb_build_object('taskId', t, 'status', 'Inactive', 'endedOn', v_work_date::text, 'changedAt', public.rfc3339_now())
    ) on conflict (event_key) do nothing;
    v_count := v_count + 1;
  end loop;
  return jsonb_build_object('ok', true, 'deactivatedCount', v_count, 'sourceWorkDate', v_work_date::text);
end;
$$;

-- ============================================================================
-- Planner RPCs
-- ============================================================================

create or replace function public.rpc_get_planner_tasks(p_payload jsonb)
returns jsonb
language sql
security definer
set search_path = public
as $$
with req as (
  select
    coalesce(p_payload->>'department','') as department,
    public.canonical_department_key(coalesce(p_payload->>'department','')) as dep_key,
    coalesce(p_payload->>'employeeName','') as employee_name,
    coalesce(public.to_date_safe(p_payload->>'workDate'), current_date) as work_date
),
latest as (
  select distinct on (coalesce(e.task_id, e.payload_json->>'taskId'))
    coalesce(e.payload_json->>'taskId', e.task_id) as task_id,
    coalesce(e.payload_json->>'title', e.title, '') as title,
    public.normalize_priority(coalesce(e.payload_json->>'priority','Medium')) as priority,
    coalesce(nullif(e.payload_json->>'plannedHours','')::int, 0) as planned_hours,
    coalesce(nullif(e.payload_json->>'plannedMinutes','')::int, 0) as planned_minutes,
    coalesce(e.payload_json->>'status', e.status, 'Open') as status,
    coalesce(e.payload_json->>'workDateRef','') as work_date_ref
  from public.task_admin_events e
  join req r on public.canonical_department_key(e.department) = r.dep_key and e.employee_name = r.employee_name
  where e.event_type = 'planner_task'
  order by coalesce(e.task_id, e.payload_json->>'taskId'), e.changed_at desc
),
open_tasks as (
  select jsonb_build_object(
    'taskId', task_id, 'title', title, 'priority', priority,
    'plannedHours', planned_hours, 'plannedMinutes', planned_minutes, 'status', 'Open'
  ) as t
  from latest where lower(status) = 'open'
),
in_sod as (
  select jsonb_build_object(
    'taskId', task_id, 'title', title, 'priority', priority,
    'plannedHours', planned_hours, 'plannedMinutes', planned_minutes, 'status', 'InSOD', 'source', 'planner'
  ) as t
  from latest, req
  where lower(status) = 'insod'
    and coalesce(work_date_ref,'') = req.work_date::text
),
consumed as (
  select distinct coalesce(e.payload_json->>'titleKey', '') as title_key
  from public.task_admin_events e
  join req r on public.canonical_department_key(e.department) = r.dep_key and e.employee_name = r.employee_name
  where e.event_type = 'planner_consumed'
)
select jsonb_build_object(
  'ok', true,
  'tasks', coalesce((select jsonb_agg(t) from open_tasks), '[]'::jsonb),
  'inSodTasks', coalesce((select jsonb_agg(t) from in_sod), '[]'::jsonb),
  'consumedTitleKeys', coalesce((select jsonb_agg(title_key) from consumed where title_key <> ''), '[]'::jsonb)
);
$$;

create or replace function public.rpc_planner_add_tasks(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  i jsonb;
  v_count int := 0;
begin
  for i in select * from jsonb_array_elements(coalesce(p_payload->'tasks','[]'::jsonb))
  loop
    insert into public.task_admin_events(event_key,event_type,changed_at,work_date,department,employee_name,task_id,title,status,payload_json)
    values (
      public.event_digest_key('planner_task', i || jsonb_build_object('status','Open','changedAt',public.rfc3339_now())),
      'planner_task', now(), null,
      coalesce(p_payload->>'department',''),
      coalesce(p_payload->>'employeeName',''),
      coalesce(nullif(i->>'taskId',''), 'pln-' || md5(clock_timestamp()::text || random()::text || coalesce(i->>'title',''))),
      i->>'title',
      'Open',
      i || jsonb_build_object('status','Open','changedAt',public.rfc3339_now(),'titleKey',lower(trim(coalesce(i->>'title',''))))
    ) on conflict (event_key) do nothing;
    v_count := v_count + 1;
  end loop;
  return jsonb_build_object('ok', true, 'addedCount', v_count, 'skippedLockedTitles', '[]'::jsonb, 'skippedExistingTitles', '[]'::jsonb);
end;
$$;

create or replace function public.rpc_planner_move_to_sod(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_work_date date := coalesce(public.to_date_safe(p_payload->>'workDate'), current_date);
  v_department text := coalesce(p_payload->>'department','');
  v_employee text := coalesce(p_payload->>'employeeName','');
  v_ids text[];
  v_id text;
  v_row record;
  v_out jsonb := '[]'::jsonb;
begin
  select coalesce(array_agg(value), '{}') into v_ids
  from jsonb_array_elements_text(coalesce(p_payload->'taskIds','[]'::jsonb));

  foreach v_id in array v_ids loop
    select
      coalesce(e.payload_json->>'taskId', e.task_id) as task_id,
      coalesce(e.payload_json->>'title', e.title, '') as title,
      public.normalize_priority(coalesce(e.payload_json->>'priority','Medium')) as priority,
      coalesce(nullif(e.payload_json->>'plannedHours','')::int, 0) as planned_hours,
      coalesce(nullif(e.payload_json->>'plannedMinutes','')::int, 0) as planned_minutes
    into v_row
    from public.task_admin_events e
    where e.event_type = 'planner_task'
      and public.canonical_department_key(e.department) = public.canonical_department_key(v_department)
      and e.employee_name = v_employee
      and coalesce(e.payload_json->>'taskId', e.task_id) = v_id
    order by e.changed_at desc
    limit 1;

    if v_row.task_id is null or coalesce(v_row.title,'') = '' then
      continue;
    end if;

    insert into public.task_admin_events(event_key,event_type,changed_at,work_date,department,employee_name,task_id,title,status,payload_json)
    values (
      public.event_digest_key('planner_task', jsonb_build_object('taskId', v_row.task_id, 'status', 'InSOD', 'workDateRef', v_work_date::text, 'changedAt', public.rfc3339_now())),
      'planner_task', now(), v_work_date, v_department, v_employee, v_row.task_id, v_row.title, 'InSOD',
      jsonb_build_object(
        'changedAt', public.rfc3339_now(),
        'department', v_department,
        'employeeName', v_employee,
        'taskId', v_row.task_id,
        'title', v_row.title,
        'titleKey', lower(trim(v_row.title)),
        'priority', v_row.priority,
        'plannedHours', v_row.planned_hours,
        'plannedMinutes', v_row.planned_minutes,
        'status', 'InSOD',
        'workDateRef', v_work_date::text
      )
    ) on conflict (event_key) do nothing;

    v_out := v_out || jsonb_build_array(jsonb_build_object(
      'taskId', v_row.task_id,
      'title', v_row.title,
      'priority', v_row.priority,
      'plannedHours', v_row.planned_hours,
      'plannedMinutes', v_row.planned_minutes,
      'source', 'planner'
    ));
  end loop;

  return jsonb_build_object('ok', true, 'movedTasks', v_out);
end;
$$;

create or replace function public.rpc_planner_return_tasks(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_work_date date := coalesce(public.to_date_safe(p_payload->>'workDate'), current_date);
  v_department text := coalesce(p_payload->>'department','');
  v_employee text := coalesce(p_payload->>'employeeName','');
  v_ids text[];
  v_id text;
  v_row record;
  v_count int := 0;
begin
  select coalesce(array_agg(value), '{}') into v_ids
  from jsonb_array_elements_text(coalesce(p_payload->'taskIds','[]'::jsonb));

  foreach v_id in array v_ids loop
    select
      coalesce(e.payload_json->>'taskId', e.task_id) as task_id,
      coalesce(e.payload_json->>'title', e.title, '') as title,
      public.normalize_priority(coalesce(e.payload_json->>'priority','Medium')) as priority,
      coalesce(nullif(e.payload_json->>'plannedHours','')::int, 0) as planned_hours,
      coalesce(nullif(e.payload_json->>'plannedMinutes','')::int, 0) as planned_minutes
    into v_row
    from public.task_admin_events e
    where e.event_type = 'planner_task'
      and public.canonical_department_key(e.department) = public.canonical_department_key(v_department)
      and e.employee_name = v_employee
      and coalesce(e.payload_json->>'taskId', e.task_id) = v_id
    order by e.changed_at desc
    limit 1;

    if v_row.task_id is null then continue; end if;

    insert into public.task_admin_events(event_key,event_type,changed_at,work_date,department,employee_name,task_id,title,status,payload_json)
    values (
      public.event_digest_key('planner_task', jsonb_build_object('taskId', v_row.task_id, 'status', 'Open', 'changedAt', public.rfc3339_now())),
      'planner_task', now(), null, v_department, v_employee, v_row.task_id, v_row.title, 'Open',
      jsonb_build_object(
        'changedAt', public.rfc3339_now(),
        'department', v_department,
        'employeeName', v_employee,
        'taskId', v_row.task_id,
        'title', v_row.title,
        'titleKey', lower(trim(v_row.title)),
        'priority', v_row.priority,
        'plannedHours', v_row.planned_hours,
        'plannedMinutes', v_row.planned_minutes,
        'status', 'Open',
        'workDateRef', ''
      )
    ) on conflict (event_key) do nothing;
    v_count := v_count + 1;
  end loop;
  return jsonb_build_object('ok', true, 'returnedCount', v_count, 'sourceWorkDate', v_work_date::text);
end;
$$;

create or replace function public.rpc_planner_mark_consumed(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_work_date date := coalesce(public.to_date_safe(p_payload->>'workDate'), current_date);
  v_department text := coalesce(p_payload->>'department','');
  v_employee text := coalesce(p_payload->>'employeeName','');
  v_ids text[];
  v_id text;
  v_row record;
  v_count int := 0;
begin
  select coalesce(array_agg(value), '{}') into v_ids
  from jsonb_array_elements_text(coalesce(p_payload->'taskIds','[]'::jsonb));

  foreach v_id in array v_ids loop
    select
      coalesce(e.payload_json->>'taskId', e.task_id) as task_id,
      coalesce(e.payload_json->>'title', e.title, '') as title,
      public.normalize_priority(coalesce(e.payload_json->>'priority','Medium')) as priority,
      coalesce(nullif(e.payload_json->>'plannedHours','')::int, 0) as planned_hours,
      coalesce(nullif(e.payload_json->>'plannedMinutes','')::int, 0) as planned_minutes
    into v_row
    from public.task_admin_events e
    where e.event_type = 'planner_task'
      and public.canonical_department_key(e.department) = public.canonical_department_key(v_department)
      and e.employee_name = v_employee
      and coalesce(e.payload_json->>'taskId', e.task_id) = v_id
    order by e.changed_at desc
    limit 1;

    if v_row.task_id is null then continue; end if;

    insert into public.task_admin_events(event_key,event_type,changed_at,work_date,department,employee_name,task_id,title,status,payload_json)
    values (
      public.event_digest_key('planner_task', jsonb_build_object('taskId', v_row.task_id, 'status', 'Consumed', 'workDateRef', v_work_date::text, 'changedAt', public.rfc3339_now())),
      'planner_task', now(), v_work_date, v_department, v_employee, v_row.task_id, v_row.title, 'Consumed',
      jsonb_build_object(
        'changedAt', public.rfc3339_now(),
        'department', v_department,
        'employeeName', v_employee,
        'taskId', v_row.task_id,
        'title', v_row.title,
        'titleKey', lower(trim(v_row.title)),
        'priority', v_row.priority,
        'plannedHours', v_row.planned_hours,
        'plannedMinutes', v_row.planned_minutes,
        'status', 'Consumed',
        'workDateRef', v_work_date::text,
        'consumedOn', v_work_date::text
      )
    ) on conflict (event_key) do nothing;

    insert into public.task_admin_events(event_key,event_type,changed_at,work_date,department,employee_name,task_id,title,status,payload_json)
    values (
      public.event_digest_key('planner_consumed', jsonb_build_object('titleKey', lower(trim(v_row.title)), 'taskId', v_row.task_id, 'consumedOn', v_work_date::text)),
      'planner_consumed', now(), v_work_date, v_department, v_employee, v_row.task_id, v_row.title, 'Consumed',
      jsonb_build_object(
        'changedAt', public.rfc3339_now(),
        'department', v_department,
        'employeeName', v_employee,
        'titleKey', lower(trim(v_row.title)),
        'sourceTaskId', v_row.task_id,
        'consumedOn', v_work_date::text
      )
    ) on conflict (event_key) do nothing;
    v_count := v_count + 1;
  end loop;

  return jsonb_build_object('ok', true, 'consumedCount', v_count);
end;
$$;

create or replace function public.rpc_planner_update_task(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_department text := coalesce(p_payload->>'department','');
  v_employee text := coalesce(p_payload->>'employeeName','');
  v_task_id text := coalesce(p_payload->>'taskId','');
  v_title text := coalesce(p_payload->>'title','');
  v_priority text := public.normalize_priority(coalesce(p_payload->>'priority','Medium'));
  v_h int := coalesce(nullif(p_payload->>'plannedHours','')::int, 0);
  v_m int := coalesce(nullif(p_payload->>'plannedMinutes','')::int, 0);
begin
  insert into public.task_admin_events(event_key,event_type,changed_at,work_date,department,employee_name,task_id,title,status,payload_json)
  values (
    public.event_digest_key('planner_task', jsonb_build_object('taskId', v_task_id, 'status', 'Open', 'title', v_title, 'changedAt', public.rfc3339_now())),
    'planner_task', now(), null, v_department, v_employee, v_task_id, v_title, 'Open',
    jsonb_build_object(
      'changedAt', public.rfc3339_now(),
      'department', v_department,
      'employeeName', v_employee,
      'taskId', v_task_id,
      'title', v_title,
      'titleKey', lower(trim(v_title)),
      'priority', v_priority,
      'plannedHours', greatest(v_h, 0),
      'plannedMinutes', greatest(v_m, 0),
      'status', 'Open',
      'workDateRef', ''
    )
  ) on conflict (event_key) do nothing;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.rpc_planner_delete_task(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_department text := coalesce(p_payload->>'department','');
  v_employee text := coalesce(p_payload->>'employeeName','');
  v_task_id text := coalesce(p_payload->>'taskId','');
begin
  insert into public.task_admin_events(event_key,event_type,changed_at,work_date,department,employee_name,task_id,title,status,payload_json)
  values (
    public.event_digest_key('planner_task', jsonb_build_object('taskId', v_task_id, 'status', 'Deleted', 'changedAt', public.rfc3339_now())),
    'planner_task', now(), null, v_department, v_employee, v_task_id, '', 'Deleted',
    jsonb_build_object(
      'changedAt', public.rfc3339_now(),
      'department', v_department,
      'employeeName', v_employee,
      'taskId', v_task_id,
      'status', 'Deleted',
      'workDateRef', ''
    )
  ) on conflict (event_key) do nothing;
  return jsonb_build_object('ok', true);
end;
$$;

-- ============================================================================
-- Admin RPCs
-- ============================================================================

create or replace function public.rpc_get_user_directory(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin text := coalesce(p_payload->>'admin', '');
  v_code text := coalesce(p_payload->>'code', '');
  v_allowed jsonb;
  v_res jsonb;
begin
  select a.allowed_departments_json
  into v_allowed
  from public.admins_directory a
  where lower(trim(a.admin_name)) = lower(trim(v_admin))
    and a.active = true
    and public.secret_matches(v_code, a.admin_code_hash)
  limit 1;

  if v_allowed is null then
    return jsonb_build_object('ok', false, 'message', 'Unauthorized');
  end if;

  with u as (
    select u0.department, u0.employee_name, u0.email
    from public.users_directory u0
    where u0.active = true
      and (
        (v_allowed ? 'All')
        or exists (
          select 1
          from jsonb_array_elements_text(v_allowed) d(dep)
          where public.canonical_department_key(d.dep) = public.canonical_department_key(u0.department)
        )
      )
  )
  select jsonb_build_object(
    'ok', true,
    'directory', coalesce((
      select jsonb_object_agg(d.department, d.people)
      from (
        select department, jsonb_object_agg(employee_name, 'MASKED') as people
        from u
        group by department
      ) d
    ), '{}'::jsonb),
    'emailDirectory', coalesce((
      select jsonb_object_agg(d.department, d.people)
      from (
        select department, jsonb_object_agg(employee_name, coalesce(email,'')) as people
        from u
        group by department
      ) d
    ), '{}'::jsonb)
  )
  into v_res;

  return v_res;
end;
$$;

create or replace function public.rpc_assign_tasks(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  i jsonb;
  v_count int := 0;
  v_work_date date := coalesce(public.to_date_safe(p_payload->>'workDate'), current_date);
begin
  for i in select * from jsonb_array_elements(coalesce(p_payload->'tasks','[]'::jsonb))
  loop
    insert into public.task_admin_events(event_key,event_type,changed_at,work_date,department,employee_name,task_id,title,status,payload_json)
    values (
      public.event_digest_key('assignment', i || jsonb_build_object('workDate', v_work_date::text)),
      'assignment', now(), v_work_date,
      coalesce(p_payload->>'department',''),
      coalesce(p_payload->>'employeeName',''),
      coalesce(nullif(i->>'taskId',''), 'asg-' || md5(clock_timestamp()::text || random()::text || coalesce(i->>'title',''))),
      coalesce(i->>'title',''),
      'Assigned',
      i || jsonb_build_object(
        'assignedAt', public.rfc3339_now(),
        'workDate', v_work_date::text,
        'department', coalesce(p_payload->>'department',''),
        'employeeName', coalesce(p_payload->>'employeeName',''),
        'assignedBy', coalesce(p_payload->>'admin',''),
        'status', 'Assigned'
      )
    ) on conflict (event_key) do nothing;
    v_count := v_count + 1;
  end loop;
  return jsonb_build_object(
    'ok', true,
    'assignedCount', v_count,
    'workDate', v_work_date::text,
    'department', coalesce(p_payload->>'department',''),
    'employeeName', coalesce(p_payload->>'employeeName','')
  );
end;
$$;

create or replace function public.rpc_create_user(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_department text := coalesce(p_payload->>'department','');
  v_name text := coalesce(p_payload->>'employeeName', p_payload->>'name', '');
  v_code text := coalesce(p_payload->>'accessCode','');
  v_email text := coalesce(p_payload->>'email','');
begin
  if v_department = '' or v_name = '' then
    return jsonb_build_object('ok', false, 'message', 'department and employeeName are required.');
  end if;

  insert into public.users_directory(department, employee_name, access_code_hash, email, changed_by, source, active)
  values (
    v_department,
    v_name,
    public.hash_secret(case when v_code = '' then 'TEMP-CHANGE-ME' else v_code end),
    v_email,
    coalesce(p_payload->>'admin',''),
    'rpc_create_user',
    true
  )
  on conflict (department, employee_name) do update
  set email = excluded.email, changed_at = now(), changed_by = excluded.changed_by;

  return jsonb_build_object(
    'ok', true,
    'role', coalesce(p_payload->>'role', 'User'),
    'department', v_department,
    'employeeName', v_name,
    'accessCode', v_code,
    'email', v_email
  );
end;
$$;

create or replace function public.rpc_log_cliq_failure(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin text := coalesce(p_payload->>'admin', '');
  v_code text := coalesce(p_payload->>'code', '');
  v_stage text := upper(coalesce(p_payload->>'stage', ''));
  v_department text := coalesce(p_payload->>'department', '');
  v_employee text := coalesce(p_payload->>'employeeName', '');
  v_work_date date := public.to_date_safe(p_payload->>'workDate');
  v_error text := left(coalesce(p_payload->>'error', 'Unknown webhook error'), 1000);
  v_flow_payload jsonb := coalesce(p_payload->'flowPayload', '{}'::jsonb);
  v_allowed jsonb;
  v_event_key text;
begin
  if v_stage not in ('SOD', 'EOD') then
    return jsonb_build_object('ok', false, 'message', 'Invalid stage');
  end if;

  select a.allowed_departments_json
  into v_allowed
  from public.admins_directory a
  where lower(trim(a.admin_name)) = lower(trim(v_admin))
    and a.active = true
    and public.secret_matches(v_code, a.admin_code_hash)
  limit 1;

  if v_allowed is null then
    return jsonb_build_object('ok', false, 'message', 'Unauthorized');
  end if;

  if not (
    (v_allowed ? 'All')
    or exists (
      select 1
      from jsonb_array_elements_text(v_allowed) d(dep)
      where public.canonical_department_key(d.dep) = public.canonical_department_key(v_department)
    )
  ) then
    return jsonb_build_object('ok', false, 'message', 'Unauthorized department');
  end if;

  v_event_key := public.event_digest_key(
    'cliq_webhook',
    jsonb_build_object(
      'nonce', clock_timestamp()::text,
      'stage', v_stage,
      'department', v_department,
      'employeeName', v_employee,
      'workDate', coalesce(v_work_date::text, '')
    )
  );

  insert into public.task_admin_events(
    event_key, event_type, changed_at, work_date, department, employee_name, task_id, title, status, payload_json
  )
  values (
    v_event_key,
    'cliq_webhook',
    now(),
    v_work_date,
    coalesce(v_department, ''),
    coalesce(v_employee, ''),
    null,
    concat(v_stage, ' Cliq webhook'),
    'Failed',
    jsonb_build_object(
      'stage', v_stage,
      'error', v_error,
      'retryCount', 0,
      'flowPayload', v_flow_payload,
      'loggedBy', v_admin,
      'loggedAt', public.rfc3339_now()
    )
  );

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.rpc_get_failed_cliq_logs(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin text := coalesce(p_payload->>'admin', '');
  v_code text := coalesce(p_payload->>'code', '');
  v_stage_filter text := upper(coalesce(p_payload->>'stage', 'All'));
  v_limit int := least(1000, greatest(1, coalesce(nullif(p_payload->>'limit','')::int, 200)));
  v_allowed jsonb;
  v_logs jsonb;
begin
  select a.allowed_departments_json
  into v_allowed
  from public.admins_directory a
  where lower(trim(a.admin_name)) = lower(trim(v_admin))
    and a.active = true
    and public.secret_matches(v_code, a.admin_code_hash)
  limit 1;

  if v_allowed is null then
    return jsonb_build_object('ok', false, 'message', 'Unauthorized');
  end if;

  with rows as (
    select
      e.id,
      e.changed_at,
      e.work_date,
      e.department,
      e.employee_name,
      coalesce(e.payload_json->>'stage', '') as stage,
      coalesce(e.payload_json->>'error', '') as error,
      coalesce((e.payload_json->>'retryCount')::int, 0) as retry_count,
      coalesce(e.payload_json->>'loggedBy', '') as logged_by,
      coalesce(e.payload_json->'flowPayload', '{}'::jsonb) as flow_payload
    from public.task_admin_events e
    where e.event_type = 'cliq_webhook'
      and e.status = 'Failed'
      and (
        (v_allowed ? 'All')
        or exists (
          select 1
          from jsonb_array_elements_text(v_allowed) d(dep)
          where public.canonical_department_key(d.dep) = public.canonical_department_key(e.department)
        )
      )
      and (v_stage_filter = 'ALL' or upper(coalesce(e.payload_json->>'stage', '')) = v_stage_filter)
    order by e.changed_at desc
    limit v_limit
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', r.id,
    'changedAt', r.changed_at,
    'workDate', r.work_date,
    'department', r.department,
    'employeeName', r.employee_name,
    'stage', r.stage,
    'error', r.error,
    'retryCount', r.retry_count,
    'loggedBy', r.logged_by,
    'flowPayload', r.flow_payload
  )), '[]'::jsonb)
  into v_logs
  from rows r;

  return jsonb_build_object('ok', true, 'logs', coalesce(v_logs, '[]'::jsonb));
end;
$$;

create or replace function public.rpc_resolve_failed_cliq_log(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin text := coalesce(p_payload->>'admin', '');
  v_code text := coalesce(p_payload->>'code', '');
  v_id bigint := coalesce(nullif(p_payload->>'id','')::bigint, 0);
  v_resolution text := coalesce(nullif(p_payload->>'resolution',''), 'sent');
  v_allowed jsonb;
begin
  if v_id <= 0 then
    return jsonb_build_object('ok', false, 'message', 'Invalid id');
  end if;

  select a.allowed_departments_json
  into v_allowed
  from public.admins_directory a
  where lower(trim(a.admin_name)) = lower(trim(v_admin))
    and a.active = true
    and public.secret_matches(v_code, a.admin_code_hash)
  limit 1;

  if v_allowed is null then
    return jsonb_build_object('ok', false, 'message', 'Unauthorized');
  end if;

  update public.task_admin_events e
  set
    status = 'Resolved',
    changed_at = now(),
    payload_json = coalesce(e.payload_json, '{}'::jsonb) || jsonb_build_object(
      'resolvedAt', public.rfc3339_now(),
      'resolvedBy', v_admin,
      'resolution', v_resolution,
      'retryCount', coalesce((e.payload_json->>'retryCount')::int, 0) + 1
    )
  where e.id = v_id
    and e.event_type = 'cliq_webhook'
    and e.status = 'Failed'
    and (
      (v_allowed ? 'All')
      or exists (
        select 1
        from jsonb_array_elements_text(v_allowed) d(dep)
        where public.canonical_department_key(d.dep) = public.canonical_department_key(e.department)
      )
    );

  if not found then
    return jsonb_build_object('ok', false, 'message', 'Log not found or already resolved.');
  end if;

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.rpc_get_admin_dashboard(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin text := coalesce(p_payload->>'admin', '');
  v_code text := coalesce(p_payload->>'code', '');
  v_anchor_date date := coalesce(public.to_date_safe(p_payload->>'workDate'), current_date);
  v_range text := lower(coalesce(p_payload->>'rangePreset', 'custom_day'));
  v_department_filter text := coalesce(p_payload->>'department', 'All');
  v_employee_filter text := coalesce(p_payload->>'employeeName', 'All');
  v_stage_filter text := coalesce(p_payload->>'stage', 'All');
  v_carryover_limit int := least(2000, greatest(50, coalesce(nullif(p_payload->>'carryoverLimit','')::int, 500)));
  v_completed_limit int := least(2000, greatest(50, coalesce(nullif(p_payload->>'completedLimit','')::int, 500)));
  v_from_date date;
  v_to_date date;
  v_days int;
  v_allowed jsonb;
  v_res jsonb;
begin
  select allowed_departments_json
  into v_allowed
  from public.admins_directory a
  where lower(trim(a.admin_name)) = lower(trim(v_admin))
    and a.active = true
    and public.secret_matches(v_code, a.admin_code_hash)
  limit 1;

  if v_allowed is null then
    return jsonb_build_object('ok', false, 'message', 'Unauthorized');
  end if;

  if v_range = 'last7' then
    v_from_date := v_anchor_date - 6;
    v_to_date := v_anchor_date;
  elsif v_range = 'last30' then
    v_from_date := v_anchor_date - 29;
    v_to_date := v_anchor_date;
  elsif v_range = 'last90' then
    v_from_date := v_anchor_date - 89;
    v_to_date := v_anchor_date;
  else
    v_from_date := v_anchor_date;
    v_to_date := v_anchor_date;
  end if;
  v_days := greatest(1, (v_to_date - v_from_date + 1));

  with emp as (
    select
      u.department,
      u.employee_name,
      public.canonical_department_key(u.department) as dep_key,
      lower(trim(u.employee_name)) as emp_key
    from public.users_directory u
    where u.active = true
      and (
        (v_allowed ? 'All')
        or exists (
          select 1
          from jsonb_array_elements_text(v_allowed) d(dep)
          where public.canonical_department_key(d.dep) = public.canonical_department_key(u.department)
        )
      )
      and (v_department_filter = 'All' or public.canonical_department_key(u.department) = public.canonical_department_key(v_department_filter))
      and (v_employee_filter = 'All' or lower(trim(u.employee_name)) = lower(trim(v_employee_filter)))
  ),
  sod_latest as (
    select distinct on (e.department, e.employee_name, s.work_date)
      e.department, e.employee_name, s.work_date, s.submitted_at, s.task_count, s.payload_json
    from public.task_submissions s
    join emp e
      on public.canonical_department_key(s.department) = e.dep_key
     and lower(trim(s.employee_name)) = e.emp_key
    where s.stage = 'SOD'
      and s.work_date between v_from_date and v_to_date
    order by e.department, e.employee_name, s.work_date, s.submitted_at desc
  ),
  eod_latest as (
    select distinct on (e.department, e.employee_name, s.work_date)
      e.department, e.employee_name, s.work_date, s.submitted_at, s.task_count, s.total_spent_minutes, s.payload_json
    from public.task_submissions s
    join emp e
      on public.canonical_department_key(s.department) = e.dep_key
     and lower(trim(s.employee_name)) = e.emp_key
    where s.stage = 'EOD'
      and s.work_date between v_from_date and v_to_date
    order by e.department, e.employee_name, s.work_date, s.submitted_at desc
  ),
  eod_all_latest as (
    select distinct on (e.department, e.employee_name, s.work_date)
      e.department, e.employee_name, s.work_date, s.submitted_at, s.task_count, s.total_spent_minutes, s.payload_json
    from public.task_submissions s
    join emp e
      on public.canonical_department_key(s.department) = e.dep_key
     and lower(trim(s.employee_name)) = e.emp_key
    where s.stage = 'EOD'
      and s.work_date <= v_to_date
    order by e.department, e.employee_name, s.work_date, s.submitted_at desc
  ),
  eod_range_updates as (
    select
      e.department,
      e.employee_name,
      coalesce(nullif(u->>'completionPercent','')::int, nullif(u->>'completion','')::int, nullif(u->>'progress','')::int) as completion
    from eod_latest e,
    lateral jsonb_array_elements(coalesce(e.payload_json->'updates', '[]'::jsonb)) u
    where coalesce(u->>'title','') <> ''
  ),
  eod_updates_all as (
    select
      e.department,
      e.employee_name,
      e.work_date,
      e.submitted_at,
      row_number() over (
        partition by e.department, e.employee_name, e.work_date, e.submitted_at
        order by coalesce(u->>'taskId', lower(coalesce(u->>'title','')))
      ) as row_ord,
      coalesce(u->>'taskId', '') as task_id,
      coalesce(u->>'title', '') as title,
      coalesce(nullif(u->>'taskId',''), lower(coalesce(u->>'title',''))) as task_key,
      coalesce(
        nullif(u->>'completionPercent','')::int,
        nullif(u->>'completion','')::int,
        nullif(u->>'progress','')::int,
        0
      )::int as completion
    from eod_all_latest e,
    lateral jsonb_array_elements(coalesce(e.payload_json->'updates', '[]'::jsonb)) u
    where coalesce(u->>'title','') <> ''
  ),
  ordered_updates as (
    select
      x.*,
      sum(case when x.completion >= 100 then 1 else 0 end) over (
        partition by x.department, x.employee_name, x.task_key
        order by x.work_date, x.submitted_at, x.row_ord
        rows between unbounded preceding and current row
      ) as reset_count,
      lag(x.completion) over (
        partition by x.department, x.employee_name, x.task_key
        order by x.work_date, x.submitted_at, x.row_ord
      ) as prev_completion,
      row_number() over (
        partition by x.department, x.employee_name, x.task_key
        order by x.work_date desc, x.submitted_at desc, x.row_ord desc
      ) as latest_rn
    from eod_updates_all x
  ),
  low_groups as (
    select
      department,
      employee_name,
      task_key,
      reset_count,
      min(work_date) as carry_start_date,
      max(work_date) as last_updated_date
    from ordered_updates
    where completion < 100
    group by department, employee_name, task_key, reset_count
  ),
  open_carry_rows as (
    select
      l.department,
      l.employee_name,
      coalesce(nullif(o.title,''), '(untitled)') as title,
      o.completion as completion_percent,
      l.carry_start_date as pending_since_date,
      l.last_updated_date as last_updated_date,
      public.count_working_days_excluding_sunday_and_leave(
        l.carry_start_date,
        v_to_date,
        o.department,
        o.employee_name
      ) as pending_working_days
    from ordered_updates o
    join low_groups l
      on l.department = o.department
     and l.employee_name = o.employee_name
     and l.task_key = o.task_key
     and l.reset_count = o.reset_count
    where o.latest_rn = 1
      and o.completion < 100
  ),
  completed_rows as (
    select
      o.department,
      o.employee_name,
      coalesce(nullif(o.title,''), '(untitled)') as title,
      coalesce(l.carry_start_date, o.work_date) as added_date,
      o.work_date as completed_date,
      public.count_working_days_excluding_sunday_and_leave(
        coalesce(l.carry_start_date, o.work_date),
        o.work_date,
        o.department,
        o.employee_name
      ) as days_taken_working,
      o.submitted_at
    from ordered_updates o
    left join low_groups l
      on l.department = o.department
     and l.employee_name = o.employee_name
     and l.task_key = o.task_key
     and l.reset_count = greatest(o.reset_count - 1, 0)
    where o.completion >= 100
      and (o.prev_completion is null or o.prev_completion < 100)
      and o.work_date between v_from_date and v_to_date
  ),
  assign_counts as (
    select e.department, e.employee_name, count(*)::int as assigned_tasks
    from public.task_admin_events e
    join emp u
      on public.canonical_department_key(e.department) = u.dep_key
     and lower(trim(e.employee_name)) = u.emp_key
    where e.event_type = 'assignment'
      and coalesce(e.work_date, v_to_date) between v_from_date and v_to_date
      and lower(coalesce(e.status,'')) = 'assigned'
    group by e.department, e.employee_name
  ),
  open_carry as (
    select c.department, c.employee_name, count(*)::int as open_carryover
    from open_carry_rows c
    group by c.department, c.employee_name
  ),
  open_carry_rows_limited as (
    select *
    from open_carry_rows
    order by pending_working_days desc, employee_name, title
    limit v_carryover_limit
  ),
  completed_rows_limited as (
    select *
    from completed_rows
    order by completed_date desc, submitted_at desc, department, employee_name, title
    limit v_completed_limit
  ),
  employee_rows as (
    select
      e.employee_name,
      e.department,
      coalesce((select count(*) from sod_latest s where s.department=e.department and s.employee_name=e.employee_name), 0)::int as sod_submitted_days,
      coalesce((select count(*) from eod_latest d where d.department=e.department and d.employee_name=e.employee_name), 0)::int as eod_submitted_days,
      greatest(
        coalesce((select count(*) from sod_latest s where s.department=e.department and s.employee_name=e.employee_name), 0)
        - coalesce((select count(*) from eod_latest d where d.department=e.department and d.employee_name=e.employee_name), 0),
        0
      )::int as eod_missing_days,
      coalesce((select sum(task_count) from sod_latest s where s.department=e.department and s.employee_name=e.employee_name), 0)::int as planned_tasks,
      coalesce((select sum(task_count) from eod_latest d where d.department=e.department and d.employee_name=e.employee_name), 0)::int as tasks_submitted,
      coalesce((select assigned_tasks from assign_counts a where a.department=e.department and a.employee_name=e.employee_name), 0)::int as assigned_tasks,
      coalesce((select open_carryover from open_carry c where c.department=e.department and c.employee_name=e.employee_name), 0)::int as open_carryover,
      greatest(
        coalesce((select max(s.submitted_at) from sod_latest s where s.department=e.department and s.employee_name=e.employee_name), 'epoch'::timestamptz),
        coalesce((select max(d.submitted_at) from eod_latest d where d.department=e.department and d.employee_name=e.employee_name), 'epoch'::timestamptz)
      ) as last_submission_at
    from emp e
  ),
  filtered_employee_rows as (
    select * from employee_rows
    where
      (v_stage_filter = 'All')
      or (v_stage_filter = 'SOD' and sod_submitted_days > 0)
      or (v_stage_filter = 'EOD' and eod_submitted_days > 0)
      or (v_stage_filter = 'Carryover' and open_carryover > 0)
  ),
  department_rows as (
    select
      department,
      count(*)::int as employee_count,
      coalesce(sum(sod_submitted_days),0)::int as sod_submitted_days,
      coalesce(sum(eod_submitted_days),0)::int as eod_submitted_days,
      coalesce(sum(eod_missing_days),0)::int as eod_missing_days,
      coalesce(sum(planned_tasks),0)::int as planned_tasks,
      coalesce(sum(tasks_submitted),0)::int as tasks_submitted,
      coalesce(sum(assigned_tasks),0)::int as assigned_tasks,
      coalesce(sum(open_carryover),0)::int as carryover_open_count
    from filtered_employee_rows
    group by department
  ),
  totals as (
    select
      coalesce(sum(planned_tasks),0)::int as planned_tasks,
      coalesce(sum(tasks_submitted),0)::int as tasks_submitted,
      coalesce(sum(eod_submitted_days),0)::int as eod_submitted_days,
      coalesce(sum(eod_missing_days),0)::int as eod_missing_days,
      coalesce(sum(open_carryover),0)::int as open_carryover
    from filtered_employee_rows
  ),
  completion_stats as (
    select
      coalesce(avg(completion)::numeric, 0) as completion_avg
    from eod_range_updates
    where completion is not null
  ),
  minutes_total as (
    select coalesce(sum(total_spent_minutes),0)::int as total_minutes
    from eod_latest
  )
  select jsonb_build_object(
    'ok', true,
    'kpis', jsonb_build_object(
      'plannedTasks', (select planned_tasks from totals),
      'tasksSubmittedCount', (select tasks_submitted from totals),
      'eodSubmittedCount', (select eod_submitted_days from totals),
      'eodMissingCount', (select count(*)::int from filtered_employee_rows where eod_missing_days > 0),
      'incompleteCarryoverCount', (select open_carryover from totals),
      'completionRate', (select round(completion_avg, 2) from completion_stats),
      'totalLoggedHours', round((select total_minutes from minutes_total)::numeric / 60.0, 2),
      'periodDays', v_days
    ),
    'departmentSummary', coalesce((
      select jsonb_agg(jsonb_build_object(
        'department', d.department,
        'employeeCount', d.employee_count,
        'sodSubmittedDays', d.sod_submitted_days,
        'eodSubmittedDays', d.eod_submitted_days,
        'eodMissingDays', d.eod_missing_days,
        'plannedTasks', d.planned_tasks,
        'tasksSubmitted', d.tasks_submitted,
        'assignedTasks', d.assigned_tasks,
        'carryoverOpenCount', d.carryover_open_count
      ) order by d.department)
      from department_rows d
    ), '[]'::jsonb),
    'employeeCompliance', coalesce((
      select jsonb_agg(jsonb_build_object(
        'employeeName', r.employee_name,
        'department', r.department,
        'sodSubmittedDays', r.sod_submitted_days,
        'eodSubmittedDays', r.eod_submitted_days,
        'eodMissingDays', r.eod_missing_days,
        'plannedTasks', r.planned_tasks,
        'tasksSubmitted', r.tasks_submitted,
        'assignedTasks', r.assigned_tasks,
        'openCarryover', r.open_carryover,
        'lastSubmissionAt', case when r.last_submission_at = 'epoch'::timestamptz then null else r.last_submission_at end
      ) order by r.department, r.employee_name)
      from filtered_employee_rows r
    ), '[]'::jsonb),
    'carryoverAging', coalesce((
      select jsonb_agg(jsonb_build_object(
        'employeeName', c.employee_name,
        'department', c.department,
        'title', c.title,
        'completionPercent', c.completion_percent,
        'pendingSinceDate', c.pending_since_date::text,
        'pendingWorkingDays', c.pending_working_days,
        'lastUpdatedDate', c.last_updated_date::text
      ) order by c.pending_working_days desc, c.employee_name, c.title)
      from open_carry_rows_limited c
    ), '[]'::jsonb),
    'completedTasks', coalesce((
      select jsonb_agg(jsonb_build_object(
        'title', c.title,
        'employeeName', c.employee_name,
        'department', c.department,
        'addedDate', c.added_date::text,
        'completedDate', c.completed_date::text,
        'daysTakenWorking', c.days_taken_working
      ) order by c.completed_date desc, c.submitted_at desc, c.department, c.employee_name, c.title)
      from completed_rows_limited c
    ), '[]'::jsonb),
    'meta', jsonb_build_object(
      'generatedAt', public.rfc3339_now(),
      'filters', jsonb_build_object(
        'rangePreset', coalesce(p_payload->>'rangePreset', 'custom_day'),
        'workDate', v_anchor_date::text,
        'fromDate', v_from_date::text,
        'toDate', v_to_date::text,
        'department', v_department_filter,
        'employeeName', v_employee_filter,
        'stage', v_stage_filter
      ),
      'limits', jsonb_build_object(
        'carryover', v_carryover_limit,
        'completed', v_completed_limit
      ),
      'departmentOptions', coalesce((
        select jsonb_agg(distinct u.department order by u.department)
        from public.users_directory u
        where u.active = true
          and (
            (v_allowed ? 'All')
            or exists (
              select 1
              from jsonb_array_elements_text(v_allowed) d(dep)
              where public.canonical_department_key(d.dep) = public.canonical_department_key(u.department)
            )
          )
      ), '[]'::jsonb),
      'employeeOptions', coalesce((
        select jsonb_agg(distinct u.employee_name order by u.employee_name)
        from public.users_directory u
        where u.active = true
          and (
            (v_allowed ? 'All')
            or exists (
              select 1
              from jsonb_array_elements_text(v_allowed) d(dep)
              where public.canonical_department_key(d.dep) = public.canonical_department_key(u.department)
            )
          )
          and (v_department_filter = 'All' or public.canonical_department_key(u.department) = public.canonical_department_key(v_department_filter))
      ), '[]'::jsonb)
    )
  )
  into v_res;

  return v_res;
end;
$$;

-- ============================================================================
-- One-time internal migration RPCs (service-role only)
-- ============================================================================

create or replace function public.internal_upsert_users_directory(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  r jsonb;
  v_count int := 0;
begin
  for r in select * from jsonb_array_elements(coalesce(p_payload->'rows', '[]'::jsonb))
  loop
    insert into public.users_directory (
      department, employee_name, access_code_hash, email, changed_by, source, active
    ) values (
      coalesce(r->>'department',''),
      coalesce(r->>'employeeName',''),
      public.hash_secret(coalesce(r->>'accessCode','')),
      coalesce(r->>'email',''),
      coalesce(r->>'changedBy','migration'),
      coalesce(r->>'source','migration'),
      true
    )
    on conflict (department, employee_name) do update
      set access_code_hash = excluded.access_code_hash,
          email = excluded.email,
          changed_at = now(),
          changed_by = excluded.changed_by,
          source = excluded.source,
          active = true;
    v_count := v_count + 1;
  end loop;
  return jsonb_build_object('ok', true, 'upserted', v_count);
end;
$$;

create or replace function public.internal_upsert_admins_directory(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  r jsonb;
  v_count int := 0;
begin
  for r in select * from jsonb_array_elements(coalesce(p_payload->'rows', '[]'::jsonb))
  loop
    insert into public.admins_directory (
      admin_name, admin_code_hash, role, allowed_departments_json, changed_by, source, active
    ) values (
      coalesce(r->>'adminName',''),
      public.hash_secret(coalesce(r->>'code','')),
      coalesce(r->>'role','Admin'),
      coalesce((r->>'allowedDepartments')::jsonb, '["All"]'::jsonb),
      coalesce(r->>'changedBy','migration'),
      coalesce(r->>'source','migration'),
      true
    )
    on conflict (admin_name) do update
      set admin_code_hash = excluded.admin_code_hash,
          role = excluded.role,
          allowed_departments_json = excluded.allowed_departments_json,
          changed_at = now(),
          changed_by = excluded.changed_by,
          source = excluded.source,
          active = true;
    v_count := v_count + 1;
  end loop;
  return jsonb_build_object('ok', true, 'upserted', v_count);
end;
$$;

create or replace function public.rpc_get_user_day_status(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_department text := coalesce(p_payload->>'department', p_payload->>'dept', '');
  v_employee text := coalesce(p_payload->>'employeeName', p_payload->>'name', '');
  v_code text := coalesce(p_payload->>'accessCode', p_payload->>'code', '');
  v_work_date date := coalesce(public.to_date_safe(p_payload->>'workDate'), (now() at time zone 'Asia/Kolkata')::date);
  v_status text := '';
begin
  perform 1
  from public.users_directory u
  where public.canonical_department_key(u.department) = public.canonical_department_key(v_department)
    and lower(trim(u.employee_name)) = lower(trim(v_employee))
    and u.active = true
    and public.secret_matches(v_code, u.access_code_hash)
  limit 1;
  if not found then
    return jsonb_build_object('ok', false, 'message', 'Invalid access.');
  end if;

  select coalesce(l.leave_status, '')
  into v_status
  from public.leave_days l
  where l.leave_date = v_work_date
    and public.canonical_department_key(l.department) = public.canonical_department_key(v_department)
    and lower(trim(l.employee_name)) = lower(trim(v_employee))
  order by l.updated_at desc nulls last
  limit 1;

  return jsonb_build_object(
    'ok', true,
    'workDate', v_work_date::text,
    'status', nullif(v_status, '')
  );
end;
$$;

-- ============================================================================
-- Seed: Advisory department user(s)
-- ============================================================================

insert into public.users_directory (
  department, employee_name, access_code_hash, email, changed_by, source, active
)
values (
  'Advisory',
  'Rashi Panchal',
  public.hash_secret('AD-RP-5791'),
  '',
  'migration',
  'seed',
  true
)
on conflict (department, employee_name) do update
  set access_code_hash = excluded.access_code_hash,
      email = excluded.email,
      changed_at = now(),
      changed_by = excluded.changed_by,
      source = excluded.source,
      active = true;

-- ============================================================================
-- Grants
-- ============================================================================

grant usage on schema public to anon, authenticated;

grant execute on function public.rpc_validate_user_access(jsonb) to anon, authenticated;
grant execute on function public.rpc_validate_admin_access(jsonb) to anon, authenticated;
grant execute on function public.rpc_submit_sod(jsonb) to anon, authenticated;
grant execute on function public.rpc_submit_eod(jsonb) to anon, authenticated;
grant execute on function public.rpc_get_user_streak(jsonb) to anon, authenticated;
grant execute on function public.rpc_set_user_day_status(jsonb) to anon, authenticated;
grant execute on function public.rpc_get_user_day_status(jsonb) to anon, authenticated;
grant execute on function public.rpc_get_streak_leaderboard(jsonb) to anon, authenticated;
grant execute on function public.rpc_get_carryover(jsonb) to anon, authenticated;
grant execute on function public.rpc_get_assignments(jsonb) to anon, authenticated;
grant execute on function public.rpc_get_recurring_tasks(jsonb) to anon, authenticated;
grant execute on function public.rpc_get_submitted_day_details(jsonb) to anon, authenticated;
grant execute on function public.rpc_sync_recurring_tasks(jsonb) to anon, authenticated;
grant execute on function public.rpc_complete_recurring_tasks(jsonb) to anon, authenticated;
grant execute on function public.rpc_get_planner_tasks(jsonb) to anon, authenticated;
grant execute on function public.rpc_planner_add_tasks(jsonb) to anon, authenticated;
grant execute on function public.rpc_planner_move_to_sod(jsonb) to anon, authenticated;
grant execute on function public.rpc_planner_return_tasks(jsonb) to anon, authenticated;
grant execute on function public.rpc_planner_mark_consumed(jsonb) to anon, authenticated;
grant execute on function public.rpc_planner_update_task(jsonb) to anon, authenticated;
grant execute on function public.rpc_planner_delete_task(jsonb) to anon, authenticated;
grant execute on function public.rpc_get_user_directory(jsonb) to anon, authenticated;
grant execute on function public.rpc_get_admin_dashboard(jsonb) to anon, authenticated;
grant execute on function public.rpc_assign_tasks(jsonb) to anon, authenticated;
grant execute on function public.rpc_create_user(jsonb) to anon, authenticated;
grant execute on function public.rpc_log_cliq_failure(jsonb) to anon, authenticated;
grant execute on function public.rpc_get_failed_cliq_logs(jsonb) to anon, authenticated;
grant execute on function public.rpc_resolve_failed_cliq_log(jsonb) to anon, authenticated;

revoke execute on function public.internal_upsert_users_directory(jsonb) from public, anon, authenticated;
revoke execute on function public.internal_upsert_admins_directory(jsonb) from public, anon, authenticated;
