(function initTaskAppDom(global) {
  const doc = global.document;

  global.TaskAppDom = {
    appEl: doc.getElementById("app"),
    blockedEl: doc.getElementById("blocked"),
    blockedMsgEl: doc.getElementById("blockedMsg"),
    nameLineEl: doc.getElementById("nameLine"),
    deptLineEl: doc.getElementById("deptLine"),
    streakChipEl: doc.getElementById("streakChip"),
    streakTextEl: doc.getElementById("streakText"),
    streakLeaderboardToggleEl: doc.getElementById("streakLeaderboardToggle"),
    streakPopEl: doc.getElementById("streakPop"),
    streakNoteEl: doc.getElementById("streakNote"),
    streakLeaderboardEl: doc.getElementById("streakLeaderboard"),
    streakConfettiEl: doc.getElementById("streakConfetti"),
    workDateEl: doc.getElementById("workDate"),
    taskTabButtons: Array.from(doc.querySelectorAll("[data-task-tab]")),
    taskTabSubmissionsEl: doc.getElementById("taskTabSubmissions"),
    taskTabPlannerEl: doc.getElementById("taskTabPlanner"),
    taskTabApprovalsEl: doc.getElementById("taskTabApprovals"),
    approvalsListEl: doc.getElementById("approvalsList"),
    approvalsStatusEl: doc.getElementById("approvalsStatus"),
    approvalCountCardEl: doc.getElementById("approvalCountCard"),
    prevMonthBtn: doc.getElementById("prevMonthBtn"),
    nextMonthBtn: doc.getElementById("nextMonthBtn"),
    prevDayBtn: doc.getElementById("prevDayBtn"),
    nextDayBtn: doc.getElementById("nextDayBtn"),
    monthLabelEl: doc.getElementById("monthLabel"),
    dateChipListEl: doc.getElementById("dateChipList"),
    startCountCardEl: doc.getElementById("startCountCard"),
    hoursSplitCardEl: doc.getElementById("hoursSplitCard"),
    eodElapsedTimeEl: doc.getElementById("eodElapsedTime"),
    postponedCountCardEl: doc.getElementById("postponedCountCard"),
    toastStackEl: doc.getElementById("toastStack"),
    confirmOverlayEl: doc.getElementById("confirmOverlay"),
    confirmTitleEl: doc.getElementById("confirmTitle"),
    confirmBodyEl: doc.getElementById("confirmBody"),
    confirmDetailsEl: doc.getElementById("confirmDetails"),
    confirmCancelBtn: doc.getElementById("confirmCancelBtn"),
    confirmProceedBtn: doc.getElementById("confirmProceedBtn"),
    taskEditOverlayEl: doc.getElementById("taskEditOverlay"),
    taskEditTitleEl: doc.getElementById("taskEditTitle"),
    taskEditTitleInputEl: doc.getElementById("taskEditTitleInput"),
    taskEditPriorityInputEl: doc.getElementById("taskEditPriorityInput"),
    taskEditFrequencyInputEl: doc.getElementById("taskEditFrequencyInput"),
    taskEditProjectWrapEl: doc.getElementById("taskEditProjectWrap"),
    taskEditProjectInputEl: doc.getElementById("taskEditProjectInput"),
    taskEditWeeklyWrapEl: doc.getElementById("taskEditWeeklyWrap"),
    taskEditWeeklyInputEl: doc.getElementById("taskEditWeeklyInput"),
    taskEditMonthlyWrapEl: doc.getElementById("taskEditMonthlyWrap"),
    taskEditMonthlyInputEl: doc.getElementById("taskEditMonthlyInput"),
    taskEditPlannedInputEl: doc.getElementById("taskEditPlannedInput"),
    taskEditQuickChipsEl: doc.getElementById("taskEditQuickChips"),
    taskEditErrorEl: doc.getElementById("taskEditError"),
    taskEditCancelBtn: doc.getElementById("taskEditCancelBtn"),
    taskEditSaveBtn: doc.getElementById("taskEditSaveBtn"),
    newTaskTitleEl: doc.getElementById("newTaskTitle"),
    newTaskFrequencyEl: doc.getElementById("newTaskFrequency"),
    newTaskProjectWrapEl: doc.getElementById("newTaskProjectWrap"),
    newTaskProjectEl: doc.getElementById("newTaskProject"),
    newTaskRecurrenceRowEl: doc.getElementById("newTaskRecurrenceRow"),
    newTaskWeeklyDayEl: doc.getElementById("newTaskWeeklyDay"),
    newTaskMonthlyDateEl: doc.getElementById("newTaskMonthlyDate"),
    newTaskPriorityEl: doc.getElementById("newTaskPriority"),
    newTaskPriorityGroupEl: doc.getElementById("newTaskPriorityGroup"),
    newTaskPlannedTimeEl: doc.getElementById("newTaskPlannedTime"),
    addTaskBtn: doc.getElementById("addTaskBtn"),
    plannerTaskTitleEl: doc.getElementById("plannerTaskTitle"),
    plannerDraftTasksEl: doc.getElementById("plannerDraftTasks"),
    addPlannerTaskBtn: doc.getElementById("addPlannerTaskBtn"),
    plannerComposeHeaderEl: doc.getElementById("plannerComposeHeader"),
    plannerComposeSectionEl: doc.getElementById("plannerComposeSection"),
    submitPlannerTasksBtn: doc.getElementById("submitPlannerTasksBtn"),
    clearPlannerDraftBtn: doc.getElementById("clearPlannerDraftBtn"),
    plannerTasksEl: doc.getElementById("plannerTasks"),
    plannerStatusEl: doc.getElementById("plannerStatus"),
    plannerCountCardEl: doc.getElementById("plannerCountCard"),
    plannerSelectedCountCardEl: doc.getElementById("plannerSelectedCountCard"),
    addPlannerToExtraBtn: doc.getElementById("addPlannerToExtraBtn"),
    movePlannerToSodBtn: doc.getElementById("movePlannerToSodBtn"),
    plannerToggleBtn: doc.getElementById("plannerToggleBtn"),
    plannerCloseBtn: doc.getElementById("plannerCloseBtn"),
    plannerSidebarEl: doc.getElementById("plannerSidebar"),
    plannerFocusOverlayEl: doc.getElementById("plannerFocusOverlay"),
    submitSodBtn: doc.getElementById("submitSodBtn"),
    sodSubmitMetaEl: doc.getElementById("sodSubmitMeta"),
    sodStatusEl: doc.getElementById("sodStatus"),
    sodTasksEl: doc.getElementById("sodTasks"),
    sodPanelEl: doc.querySelector('section.panel[aria-label="Start of Day"]'),
    sodSourceHintEl: doc.getElementById("sodSourceHint"),
    syncMetaLineEl: doc.getElementById("syncMetaLine"),
    saveMetaLineEl: doc.getElementById("saveMetaLine"),
    dayStatusRowEl: doc.getElementById("dayStatusRow"),
    dayStatusBtnEl: doc.getElementById("dayStatusBtn"),
    dayStatusMetaEl: doc.getElementById("dayStatusMeta"),
    sodLoginTimeMetaEl: doc.getElementById("sodLoginTimeMeta"),
    eodCheckoutTimeMetaEl: doc.getElementById("eodCheckoutTimeMeta"),
    sodBucketsEl: doc.getElementById("sodBuckets"),
    sodSelectedPreviewEl: doc.getElementById("sodSelectedPreview"),
    plannedQuickChipsEl: doc.getElementById("plannedQuickChips"),
    syncCarryoverBtn: doc.getElementById("syncCarryoverBtn"),
    openAdminBtn: doc.getElementById("openAdminBtn"),
    addExtraBtn: doc.getElementById("addExtraBtn"),
    submitEodBtn: doc.getElementById("submitEodBtn"),
    eodStatusEl: doc.getElementById("eodStatus"),
    eodTasksEl: doc.getElementById("eodTasks"),
    eodPanelEl: doc.querySelector('section.panel[aria-label="End of Day"]'),
    COMPLETION_OPTIONS: [10, 25, 50, 75, 90, 100],
    RECURRING_FREQUENCIES: ["Daily", "Weekly", "Monthly"],
    WEEKDAY_LABELS: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    SOD_POSTPONE_LIMIT: 5
  };
})(window);
