-- Zoho People attendance ingest + user-day attendance RPC
-- Run this in Supabase SQL Editor after supabase-cutover.sql.

create table if not exists public.zoho_people_user_map (
  id bigint generated by default as identity primary key,
  employeeid text not null unique,
  department text not null,
  employeename text not null,
  email text default '',
  active boolean not null default true,
  updatedat timestamptz not null default now(),
  source text default 'manual'
);

do $$
begin
  alter table public.zoho_people_user_map add column if not exists employeeid text;
  alter table public.zoho_people_user_map add column if not exists employeename text;
  alter table public.zoho_people_user_map add column if not exists email text default '';
  alter table public.zoho_people_user_map add column if not exists updatedat timestamptz default now();
  alter table public.zoho_people_user_map add column if not exists source text default 'manual';
  alter table public.zoho_people_user_map add column if not exists active boolean default true;
  alter table public.zoho_people_user_map add column if not exists employee_id_code text;
  alter table public.zoho_people_user_map add column if not exists employee_name text;
  alter table public.zoho_people_user_map add column if not exists employee_email text default '';
  alter table public.zoho_people_user_map add column if not exists updated_at timestamptz default now();

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'zoho_people_user_map' and column_name = 'employee_id_code'
  ) then
    execute 'update public.zoho_people_user_map
             set employeeid = coalesce(employeeid, employee_id_code)
             where employeeid is null';
  end if;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'zoho_people_user_map' and column_name = 'employee_name'
  ) then
    execute 'update public.zoho_people_user_map
             set employeename = coalesce(employeename, employee_name)
             where employeename is null';
  end if;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'zoho_people_user_map' and column_name = 'employee_email'
  ) then
    execute 'update public.zoho_people_user_map
             set email = coalesce(email, employee_email)
             where email is null';
  end if;

  update public.zoho_people_user_map
     set employeeid = coalesce(nullif(employeeid, ''), 'UNMAPPED-' || id::text),
         employeename = coalesce(nullif(employeename, ''), 'Unknown ' || id::text),
         email = coalesce(email, ''),
         employee_id_code = coalesce(nullif(employee_id_code, ''), nullif(employeeid, ''), 'UNMAPPED-' || id::text),
         employee_name = coalesce(nullif(employee_name, ''), nullif(employeename, ''), 'Unknown ' || id::text),
         employee_email = coalesce(employee_email, email, ''),
         active = coalesce(active, true),
         updated_at = coalesce(updated_at, updatedat, now()),
         updatedat = coalesce(updatedat, now()),
         source = coalesce(source, 'manual');

  alter table public.zoho_people_user_map alter column employeeid set not null;
  alter table public.zoho_people_user_map alter column employeename set not null;
  alter table public.zoho_people_user_map alter column active set not null;
  alter table public.zoho_people_user_map alter column updatedat set not null;
  alter table public.zoho_people_user_map alter column employee_id_code set not null;
  alter table public.zoho_people_user_map alter column employee_name set not null;
  alter table public.zoho_people_user_map alter column updated_at set not null;

  if not exists (
    select 1
    from pg_constraint c
    where c.conrelid = 'public.zoho_people_user_map'::regclass
      and c.contype = 'u'
      and c.conname = 'zoho_people_user_map_employeeid_key'
  ) then
    alter table public.zoho_people_user_map
      add constraint zoho_people_user_map_employeeid_key unique (employeeid);
  end if;
exception when others then
  null;
end $$;

create index if not exists idx_zoho_people_user_map_lookup
  on public.zoho_people_user_map (employeeid, active);

create table if not exists public.zoho_people_attendance_raw (
  raw_key text not null unique,
  "Status" text,
  "OverTime" text,
  "Description" text,
  "TotalHours" text,
  "orgID" bigint,
  "ExpectedToTime" text,
  "WorkingHours" text,
  "ToTime" text,
  "InputType" int,
  "form" text,
  "isdebug" boolean,
  "ExpectedFromTime" text,
  "id" bigint,
  "AttendanceDay" text,
  "DeviationTime" text,
  "EmployeeID" text,
  "BreakTime" text,
  "FromTime" text,
  payload_json jsonb not null default '{}'::jsonb,
  mapped boolean not null default false,
  mapped_department text,
  mapped_employee_name text,
  received_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_zoho_people_attendance_raw_day
  on public.zoho_people_attendance_raw ("AttendanceDay", "EmployeeID", received_at desc);

create table if not exists public.user_attendance_logs (
  id bigint generated by default as identity primary key,
  attendance_key text not null unique,
  source text not null default 'zoho_people',
  org_id bigint,
  attendance_day date not null,
  department text,
  employee_name text,
  employee_email text,
  employee_id_raw text,
  employee_id_code text,
  status text,
  from_time timestamptz,
  to_time timestamptz,
  working_minutes int,
  total_minutes int,
  break_minutes int,
  over_time_minutes int,
  input_type int,
  raw_payload jsonb not null default '{}'::jsonb,
  ingested_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_user_attendance_day_lookup
  on public.user_attendance_logs (attendance_day, department, employee_name, ingested_at desc);

create index if not exists idx_user_attendance_empid_lookup
  on public.user_attendance_logs (employee_id_code, attendance_day desc, ingested_at desc);

alter table public.zoho_people_user_map enable row level security;
alter table public.zoho_people_attendance_raw enable row level security;
