-- Durable, auditable streak corrections. The override is anchored to a completed
-- working day and advances only while later working days remain fully compliant.
create table if not exists public.user_streak_overrides (
  id bigint generated by default as identity primary key,
  department text not null,
  employee_name text not null,
  anchor_date date not null,
  anchor_current integer not null check (anchor_current >= 0),
  anchor_best integer not null check (anchor_best >= anchor_current),
  reason text not null,
  marked_by text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (department, employee_name)
);

alter table public.user_streak_overrides enable row level security;

do $migration$
declare
  v_definition text := pg_get_functiondef('public.compute_user_streak_from_submissions(text,text)'::regprocedure);
  v_old_declarations text := $old$
  v_broken_after_last boolean := false;
$old$;
  v_new_declarations text := $new$
  v_broken_after_last boolean := false;
  v_override record;
  v_override_contiguous boolean := false;
  v_override_increment int := 0;
$new$;
  v_old_return text := $old$
  return query
  select v_cur, v_best, v_last;
$old$;
  v_new_return text := $new$
  select o.anchor_date, o.anchor_current, o.anchor_best
  into v_override
  from public.user_streak_overrides o
  where public.canonical_department_key(o.department) = public.canonical_department_key(p_department)
    and lower(trim(o.employee_name)) = lower(trim(p_employee_name))
    and o.active = true
  limit 1;

  if v_override is not null then
    v_best := greatest(v_best, v_override.anchor_best);

    if not v_broken_after_last and v_last is not null and v_last >= v_override.anchor_date then
      with working_days as (
        select g::date as work_date
        from generate_series(v_override.anchor_date + 1, v_last, interval '1 day') g
        where public.is_working_day_for_user(g::date, p_department, p_employee_name)
      ),
      day_flags as (
        select
          s.work_date,
          bool_or(s.stage = 'SOD') as has_sod,
          bool_or(s.stage = 'EOD') as has_eod
        from public.task_submissions s
        where public.canonical_department_key(s.department) = public.canonical_department_key(p_department)
          and lower(trim(s.employee_name)) = lower(trim(p_employee_name))
          and s.work_date > v_override.anchor_date
          and s.work_date <= v_last
        group by s.work_date
      )
      select
        coalesce(bool_and(coalesce(f.has_sod, false) and coalesce(f.has_eod, false)), true),
        count(*)::int
      into v_override_contiguous, v_override_increment
      from working_days w
      left join day_flags f on f.work_date = w.work_date;

      if v_override_contiguous then
        v_cur := v_override.anchor_current + v_override_increment;
        v_best := greatest(v_best, v_cur);
      end if;
    end if;
  end if;

  return query
  select v_cur, v_best, v_last;
$new$;
begin
  if strpos(v_definition, v_new_return) > 0 then
    return;
  end if;
  if strpos(v_definition, v_old_declarations) = 0 or strpos(v_definition, v_old_return) = 0 then
    raise exception 'Streak function differs from expected definition; inspect before applying.';
  end if;
  v_definition := replace(v_definition, v_old_declarations, v_new_declarations);
  v_definition := replace(v_definition, v_old_return, v_new_return);
  execute v_definition;
end;
$migration$;

insert into public.user_streak_overrides (
  department, employee_name, anchor_date, anchor_current, anchor_best,
  reason, marked_by, active, updated_at
) values (
  'Marketing', 'Deepti Baria', date '2026-09-04', 94, 94,
  'Management-approved streak restoration', 'Pranob Thachanthara', true, now()
)
on conflict (department, employee_name) do update
set anchor_date = excluded.anchor_date,
    anchor_current = excluded.anchor_current,
    anchor_best = excluded.anchor_best,
    reason = excluded.reason,
    marked_by = excluded.marked_by,
    active = true,
    updated_at = now();

-- Keep the cache consistent for endpoints that read it directly.
insert into public.user_streaks (
  department, employee_name, current_streak, best_streak, last_counted_date, updated_at
) values (
  'Marketing', 'Deepti Baria', 94, 94, date '2026-09-04', now()
)
on conflict (department, employee_name) do update
set current_streak = 94,
    best_streak = greatest(public.user_streaks.best_streak, 94),
    last_counted_date = date '2026-09-04',
    updated_at = now();
