-- Zoho People attendance ingest + user-day attendance RPC
-- Run this in Supabase SQL Editor after supabase-cutover.sql.

create table if not exists public.zoho_people_user_map (
  id bigint generated by default as identity primary key,
  employeeid text not null unique,
  department text not null,
  employeename text not null,
  email text default '',
  active boolean not null default true,
  updatedat timestamptz not null default now(),
  source text default 'manual'
);

do $$
begin
  alter table public.zoho_people_user_map add column if not exists employeeid text;
  alter table public.zoho_people_user_map add column if not exists employeename text;
  alter table public.zoho_people_user_map add column if not exists email text default '';
  alter table public.zoho_people_user_map add column if not exists updatedat timestamptz default now();
  alter table public.zoho_people_user_map add column if not exists source text default 'manual';
  alter table public.zoho_people_user_map add column if not exists active boolean default true;
  alter table public.zoho_people_user_map add column if not exists employee_id_code text;
  alter table public.zoho_people_user_map add column if not exists employee_name text;
  alter table public.zoho_people_user_map add column if not exists employee_email text default '';
  alter table public.zoho_people_user_map add column if not exists updated_at timestamptz default now();

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'zoho_people_user_map' and column_name = 'employee_id_code'
  ) then
    execute 'update public.zoho_people_user_map
             set employeeid = coalesce(employeeid, employee_id_code)
             where employeeid is null';
  end if;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'zoho_people_user_map' and column_name = 'employee_name'
  ) then
    execute 'update public.zoho_people_user_map
             set employeename = coalesce(employeename, employee_name)
             where employeename is null';
  end if;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'zoho_people_user_map' and column_name = 'employee_email'
  ) then
    execute 'update public.zoho_people_user_map
             set email = coalesce(email, employee_email)
             where email is null';
  end if;

  update public.zoho_people_user_map
     set employeeid = coalesce(nullif(employeeid, ''), 'UNMAPPED-' || id::text),
         employeename = coalesce(nullif(employeename, ''), 'Unknown ' || id::text),
         email = coalesce(email, ''),
         employee_id_code = coalesce(nullif(employee_id_code, ''), nullif(employeeid, ''), 'UNMAPPED-' || id::text),
         employee_name = coalesce(nullif(employee_name, ''), nullif(employeename, ''), 'Unknown ' || id::text),
         employee_email = coalesce(employee_email, email, ''),
         active = coalesce(active, true),
         updated_at = coalesce(updated_at, updatedat, now()),
         updatedat = coalesce(updatedat, now()),
         source = coalesce(source, 'manual');

  alter table public.zoho_people_user_map alter column employeeid set not null;
  alter table public.zoho_people_user_map alter column employeename set not null;
  alter table public.zoho_people_user_map alter column active set not null;
  alter table public.zoho_people_user_map alter column updatedat set not null;
  alter table public.zoho_people_user_map alter column employee_id_code set not null;
  alter table public.zoho_people_user_map alter column employee_name set not null;
  alter table public.zoho_people_user_map alter column updated_at set not null;

  if not exists (
    select 1
    from pg_constraint c
    where c.conrelid = 'public.zoho_people_user_map'::regclass
      and c.contype = 'u'
      and c.conname = 'zoho_people_user_map_employeeid_key'
  ) then
    alter table public.zoho_people_user_map
      add constraint zoho_people_user_map_employeeid_key unique (employeeid);
  end if;
exception when others then
  null;
end $$;

create index if not exists idx_zoho_people_user_map_lookup
  on public.zoho_people_user_map (employeeid, active);

create table if not exists public.zoho_people_attendance_raw (
  raw_key text not null unique,
  "Status" text,
  "OverTime" text,
  "Description" text,
  "TotalHours" text,
  "orgID" bigint,
  "ExpectedToTime" text,
  "WorkingHours" text,
  "ToTime" text,
  "InputType" int,
  "form" text,
  "isdebug" boolean,
  "ExpectedFromTime" text,
  "id" bigint,
  "AttendanceDay" text,
  "DeviationTime" text,
  "EmployeeID" text,
  "BreakTime" text,
  "FromTime" text,
  payload_json jsonb not null default '{}'::jsonb,
  mapped boolean not null default false,
  mapped_department text,
  mapped_employee_name text,
  received_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_zoho_people_attendance_raw_day
  on public.zoho_people_attendance_raw ("AttendanceDay", "EmployeeID", received_at desc);

create table if not exists public.user_attendance_logs (
  id bigint generated by default as identity primary key,
  attendance_key text not null unique,
  source text not null default 'zoho_people',
  org_id bigint,
  attendance_day date not null,
  department text,
  employee_name text,
  employee_email text,
  employee_id_raw text,
  employee_id_code text,
  status text,
  from_time timestamptz,
  to_time timestamptz,
  working_minutes int,
  total_minutes int,
  break_minutes int,
  over_time_minutes int,
  input_type int,
  raw_payload jsonb not null default '{}'::jsonb,
  ingested_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_user_attendance_day_lookup
  on public.user_attendance_logs (attendance_day, department, employee_name, ingested_at desc);

create index if not exists idx_user_attendance_empid_lookup
  on public.user_attendance_logs (employee_id_code, attendance_day desc, ingested_at desc);

alter table public.zoho_people_user_map enable row level security;
alter table public.zoho_people_attendance_raw enable row level security;
alter table public.user_attendance_logs enable row level security;

create or replace function public.extract_employee_id_code(p_val text)
returns text
language sql
immutable
as $$
  select coalesce(
    (regexp_match(coalesce(p_val, ''), '(E[0-9A-Za-z]+)\s*$'))[1],
    (regexp_match(coalesce(p_val, ''), '([A-Za-z0-9]*[0-9][A-Za-z0-9]*)\s*$'))[1],
    ''
  );
$$;

create or replace function public.parse_hhmm_to_minutes(p_val text)
returns int
language plpgsql
immutable
as $$
declare
  v text := trim(coalesce(p_val, ''));
  v_h int;
  v_m int;
begin
  if v = '' then
    return null;
  end if;
  if v !~ '^\d{1,2}:\d{2}$' then
    return null;
  end if;
  v_h := split_part(v, ':', 1)::int;
  v_m := split_part(v, ':', 2)::int;
  return greatest(0, v_h * 60 + v_m);
exception when others then
  return null;
end;
$$;

create or replace function public.parse_zoho_people_date(p_val text)
returns date
language plpgsql
immutable
as $$
declare
  v date;
begin
  if trim(coalesce(p_val, '')) = '' then
    return null;
  end if;
  begin
    v := to_date(trim(p_val), 'DD-Mon-YYYY');
  exception when others then
    begin
      v := p_val::date;
    exception when others then
      v := null;
    end;
  end;
  return v;
end;
$$;

create or replace function public.parse_zoho_people_timestamp(p_val text)
returns timestamptz
language plpgsql
stable
as $$
declare
  v_ts timestamptz;
begin
  if trim(coalesce(p_val, '')) = '' then
    return null;
  end if;
  begin
    v_ts := (to_timestamp(trim(p_val), 'DD-Mon-YYYY HH24:MI:SS')::timestamp at time zone 'Asia/Kolkata');
  exception when others then
    begin
      v_ts := p_val::timestamptz;
    exception when others then
      v_ts := null;
    end;
  end;
  return v_ts;
end;
$$;

create or replace function public.parse_zoho_people_timestamp_on_day(p_val text, p_day date)
returns timestamptz
language plpgsql
stable
as $$
declare
  v text := trim(coalesce(p_val, ''));
  v_ts timestamptz;
begin
  if v = '' then
    return null;
  end if;

  v_ts := public.parse_zoho_people_timestamp(v);
  if v_ts is not null then
    return v_ts;
  end if;

  if p_day is null then
    return null;
  end if;

  begin
    v_ts := (to_timestamp(p_day::text || ' ' || v, 'YYYY-MM-DD HH24:MI:SS')::timestamp at time zone 'Asia/Kolkata');
  exception when others then
    v_ts := null;
  end;
  if v_ts is not null then return v_ts; end if;

  begin
    v_ts := (to_timestamp(p_day::text || ' ' || v, 'YYYY-MM-DD HH24:MI')::timestamp at time zone 'Asia/Kolkata');
  exception when others then
    v_ts := null;
  end;
  if v_ts is not null then return v_ts; end if;

  begin
    v_ts := (to_timestamp(p_day::text || ' ' || upper(v), 'YYYY-MM-DD HH12:MI:SS AM')::timestamp at time zone 'Asia/Kolkata');
  exception when others then
    v_ts := null;
  end;
  if v_ts is not null then return v_ts; end if;

  begin
    v_ts := (to_timestamp(p_day::text || ' ' || upper(v), 'YYYY-MM-DD HH12:MI AM')::timestamp at time zone 'Asia/Kolkata');
  exception when others then
    v_ts := null;
  end;

  return v_ts;
end;
$$;

create or replace function public.rpc_get_user_attendance(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_department text := trim(coalesce(p_payload->>'department', p_payload->>'dept', ''));
  v_employee_name text := trim(coalesce(p_payload->>'employeeName', p_payload->>'name', ''));
  v_access_code text := trim(coalesce(p_payload->>'accessCode', p_payload->>'code', ''));
  v_work_date date := coalesce(public.to_date_safe(p_payload->>'workDate'), (now() at time zone 'Asia/Kolkata')::date);
  v_is_direct_reportees boolean := (public.canonical_department_key(v_department) = 'directreportees');
  v_user_email text := '';
  v_user_employee_id_code text := '';
  v_employee_name_key text := '';
  v_day_status text := '';
  v_user record;
  v_row record;
begin
  if v_department = '' or v_employee_name = '' or v_access_code = '' then
    return jsonb_build_object('ok', false, 'message', 'Missing access payload.');
  end if;

  select
    u.department as department,
    u.employee_name as employee_name,
    coalesce(u.email, '') as email
  into v_user
  from public.users_directory u
  where u.active = true
    and (
      lower(trim(u.employee_name)) = lower(trim(v_employee_name))
      or lower(trim(u.employee_name)) like lower(trim(v_employee_name)) || '%'
      or lower(trim(v_employee_name)) like lower(trim(u.employee_name)) || '%'
    )
    and (
      v_is_direct_reportees
      or public.canonical_department_key(u.department) = public.canonical_department_key(v_department)
    )
    and public.secret_matches(v_access_code, u.access_code_hash)
  order by u.changed_at desc nulls last
  limit 1;

  if not found then
    -- Fallback for legacy/mis-tagged links where department in payload is stale.
    select
      u.department as department,
      u.employee_name as employee_name,
      coalesce(u.email, '') as email
    into v_user
    from public.users_directory u
    where u.active = true
      and (
        lower(trim(u.employee_name)) = lower(trim(v_employee_name))
        or lower(trim(u.employee_name)) like lower(trim(v_employee_name)) || '%'
        or lower(trim(v_employee_name)) like lower(trim(u.employee_name)) || '%'
      )
      and public.secret_matches(v_access_code, u.access_code_hash)
    order by u.changed_at desc nulls last
    limit 1;
  end if;

  if not found then
    return jsonb_build_object('ok', false, 'message', 'Invalid access.');
  end if;

  if v_is_direct_reportees then
    v_department := coalesce(v_user.department, v_department);
  end if;
  v_employee_name := coalesce(v_user.employee_name, v_employee_name);
  v_employee_name_key := lower(regexp_replace(coalesce(v_employee_name, ''), '[^a-z0-9]', '', 'g'));
  v_user_email := coalesce(v_user.email, '');

  if nullif(trim(v_user_email), '') is null then
    select coalesce(u.email, '')
    into v_user_email
    from public.users_directory u
    where u.active = true
      and public.canonical_department_key(u.department) = public.canonical_department_key(v_department)
      and lower(trim(u.employee_name)) = lower(trim(v_employee_name))
    order by u.changed_at desc nulls last
    limit 1;
  end if;

  select coalesce(public.extract_employee_id_code(m.employeeid), '')
  into v_user_employee_id_code
  from public.zoho_people_user_map m
  where m.active = true
    and public.canonical_department_key(m.department) = public.canonical_department_key(v_department)
    and lower(trim(m.employeename)) = lower(trim(v_employee_name))
  order by m.updatedat desc nulls last
  limit 1;

  if v_user_employee_id_code = '' then
    select coalesce(public.extract_employee_id_code(m.employeeid), '')
    into v_user_employee_id_code
    from public.zoho_people_user_map m
    where m.active = true
      and lower(trim(m.employeename)) = lower(trim(v_employee_name))
    order by m.updatedat desc nulls last
    limit 1;
  end if;

  if v_user_employee_id_code = '' then
    select coalesce(public.extract_employee_id_code(r."EmployeeID"), '')
    into v_user_employee_id_code
    from public.zoho_people_attendance_raw r
    where public.parse_zoho_people_date(r."AttendanceDay") = v_work_date
      and (
        lower(trim(regexp_replace(coalesce(r."EmployeeID", ''), '\s+E[0-9A-Za-z]+\s*$', '', 'i'))) = lower(trim(v_employee_name))
        or lower(trim(regexp_replace(coalesce(r."EmployeeID", ''), '\s+E[0-9A-Za-z]+\s*$', '', 'i'))) like lower(trim(v_employee_name)) || '%'
        or lower(trim(v_employee_name)) like lower(trim(regexp_replace(coalesce(r."EmployeeID", ''), '\s+E[0-9A-Za-z]+\s*$', '', 'i'))) || '%'
      )
    order by r.received_at desc
    limit 1;
  end if;

  select coalesce(l.leave_status, '')
  into v_day_status
  from public.leave_days l
  where l.leave_date = v_work_date
    and public.canonical_department_key(l.department) = public.canonical_department_key(v_department)
    and lower(trim(l.employee_name)) = lower(trim(v_employee_name))
  order by l.updated_at desc nulls last
  limit 1;

  select
    count(*)::int as row_count,
    min(l.from_time) filter (where l.from_time is not null) as first_in_time,
    max(l.to_time) filter (where l.to_time is not null) as last_out_time,
    max(l.working_minutes) as working_minutes,
    max(l.total_minutes) as total_minutes,
    (array_agg(l.source order by coalesce(l.to_time, l.from_time) desc nulls last, l.ingested_at desc)
      filter (where coalesce(l.source, '') <> ''))[1] as source,
    (array_agg(l.status order by coalesce(l.to_time, l.from_time) desc nulls last, l.ingested_at desc)
      filter (where coalesce(l.status, '') <> ''))[1] as status,
    (array_agg(l.employee_email order by l.ingested_at desc)
      filter (where coalesce(l.employee_email, '') <> ''))[1] as employee_email,
    (array_agg(l.employee_id_raw order by l.ingested_at desc)
      filter (where coalesce(l.employee_id_raw, '') <> ''))[1] as employee_id_raw,
    (array_agg(l.employee_id_code order by l.ingested_at desc)
      filter (where coalesce(l.employee_id_code, '') <> ''))[1] as employee_id_code,
    max(l.ingested_at) as ingested_at
  into v_row
  from public.user_attendance_logs l
  where l.attendance_day = v_work_date
    and (
      (
        public.canonical_department_key(coalesce(l.department, '')) = public.canonical_department_key(v_department)
        and (
          nullif(trim(coalesce(l.employee_name, '')), '') is not null
          and (
            lower(trim(coalesce(l.employee_name, ''))) = lower(trim(v_employee_name))
            or lower(trim(coalesce(l.employee_name, ''))) like lower(trim(v_employee_name)) || '%'
            or lower(trim(v_employee_name)) like lower(trim(coalesce(l.employee_name, ''))) || '%'
            or lower(regexp_replace(coalesce(l.employee_name, ''), '[^a-z0-9]', '', 'g')) = v_employee_name_key
            or lower(regexp_replace(coalesce(l.employee_name, ''), '[^a-z0-9]', '', 'g')) like v_employee_name_key || '%'
            or v_employee_name_key like lower(regexp_replace(coalesce(l.employee_name, ''), '[^a-z0-9]', '', 'g')) || '%'
          )
        )
      )
      or (
        nullif(trim(coalesce(l.employee_name, '')), '') is not null
        and (
          lower(trim(coalesce(l.employee_name, ''))) = lower(trim(v_employee_name))
          or lower(trim(coalesce(l.employee_name, ''))) like lower(trim(v_employee_name)) || '%'
          or lower(trim(v_employee_name)) like lower(trim(coalesce(l.employee_name, ''))) || '%'
          or lower(regexp_replace(coalesce(l.employee_name, ''), '[^a-z0-9]', '', 'g')) = v_employee_name_key
          or lower(regexp_replace(coalesce(l.employee_name, ''), '[^a-z0-9]', '', 'g')) like v_employee_name_key || '%'
          or v_employee_name_key like lower(regexp_replace(coalesce(l.employee_name, ''), '[^a-z0-9]', '', 'g')) || '%'
        )
      )
      or (
        nullif(trim(v_user_email), '') is not null
        and lower(trim(coalesce(l.employee_email, ''))) = lower(trim(v_user_email))
      )
      or (
        nullif(trim(v_user_employee_id_code), '') is not null
        and (
          lower(trim(coalesce(l.employee_id_code, ''))) = lower(trim(v_user_employee_id_code))
          or lower(trim(public.extract_employee_id_code(coalesce(l.employee_id_raw, '')))) = lower(trim(v_user_employee_id_code))
        )
      )
    );

  if coalesce(v_row.row_count, 0) = 0 then
    return jsonb_build_object(
      'ok', true,
      'workDate', v_work_date::text,
      'dayStatus', nullif(v_day_status, ''),
      'attendance', null
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'workDate', v_work_date::text,
    'dayStatus', nullif(v_day_status, ''),
    'attendance', jsonb_build_object(
      'loginTime', case when v_row.first_in_time is null then '' else to_char(v_row.first_in_time at time zone 'Asia/Kolkata', 'HH24:MI') end,
      'logoutTime', case when v_row.last_out_time is null then '' else to_char(v_row.last_out_time at time zone 'Asia/Kolkata', 'HH24:MI') end,
      'workingMinutes', case
        when v_row.first_in_time is not null
         and v_row.last_out_time is not null
         and v_row.last_out_time >= v_row.first_in_time
        then floor(extract(epoch from (v_row.last_out_time - v_row.first_in_time)) / 60)::int
        else coalesce(v_row.working_minutes, v_row.total_minutes)
      end,
      'status', coalesce(v_row.status, ''),
      'source', coalesce(v_row.source, 'zoho_people'),
      'employeeEmail', coalesce(v_row.employee_email, ''),
      'employeeId', coalesce(v_row.employee_id_raw, ''),
      'employeeIdCode', coalesce(v_row.employee_id_code, ''),
      'ingestedAt', v_row.ingested_at
    )
  );
end;
$$;

create or replace function public.internal_ingest_zoho_people_attendance(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_payload jsonb := coalesce(case when jsonb_typeof(p_payload) = 'object' then p_payload else '{}'::jsonb end, '{}'::jsonb);
  v_department text := trim(coalesce(v_payload->>'department', v_payload->>'Department', ''));
  v_employee_name text := trim(coalesce(v_payload->>'employeeName', v_payload->>'EmployeeName', v_payload->>'name', ''));
  v_employee_email text := trim(coalesce(v_payload->>'employeeEmail', v_payload->>'Email', v_payload->>'email', ''));
  v_employee_id_raw text := trim(coalesce(v_payload->>'EmployeeID', v_payload->>'employeeId', ''));
  v_employee_id_code text := public.extract_employee_id_code(v_employee_id_raw);
  v_attendance_day date := coalesce(
    public.parse_zoho_people_date(v_payload->>'AttendanceDay'),
    public.parse_zoho_people_date(v_payload->>'attendanceDay'),
    public.to_date_safe(v_payload->>'workDate')
  );
  v_from_time timestamptz := coalesce(
    public.parse_zoho_people_timestamp_on_day(v_payload->>'FromTime', v_attendance_day),
    public.parse_zoho_people_timestamp_on_day(v_payload->>'fromTime', v_attendance_day),
    public.parse_zoho_people_timestamp_on_day(v_payload->>'loginTime', v_attendance_day)
  );
  v_to_time timestamptz := coalesce(
    public.parse_zoho_people_timestamp_on_day(v_payload->>'ToTime', v_attendance_day),
    public.parse_zoho_people_timestamp_on_day(v_payload->>'toTime', v_attendance_day),
    public.parse_zoho_people_timestamp_on_day(v_payload->>'logoutTime', v_attendance_day)
  );
  v_status text := trim(coalesce(v_payload->>'Status', v_payload->>'status', ''));
  v_source text := trim(coalesce(v_payload->>'source', 'zoho_people'));
  v_working_minutes int := coalesce(
    public.parse_hhmm_to_minutes(v_payload->>'WorkingHours'),
    public.parse_hhmm_to_minutes(v_payload->>'workingHours')
  );
  v_total_minutes int := coalesce(
    public.parse_hhmm_to_minutes(v_payload->>'TotalHours'),
    public.parse_hhmm_to_minutes(v_payload->>'totalHours')
  );
  v_break_minutes int := coalesce(
    public.parse_hhmm_to_minutes(v_payload->>'BreakTime'),
    public.parse_hhmm_to_minutes(v_payload->>'breakTime')
  );
  v_over_time_minutes int := coalesce(
    public.parse_hhmm_to_minutes(v_payload->>'OverTime'),
    public.parse_hhmm_to_minutes(v_payload->>'overTime')
  );
  v_input_type int := case when coalesce(v_payload->>'InputType','') ~ '^-?\d+$' then (v_payload->>'InputType')::int else null end;
  v_org_id bigint := case when coalesce(v_payload->>'orgID','') ~ '^-?\d+$' then (v_payload->>'orgID')::bigint else null end;
  v_record_id bigint := case when coalesce(v_payload->>'id','') ~ '^-?\d+$' then (v_payload->>'id')::bigint else null end;
  v_isdebug boolean := case lower(coalesce(v_payload->>'isdebug', ''))
    when 'true' then true
    when '1' then true
    when 'yes' then true
    when 'false' then false
    when '0' then false
    when 'no' then false
    else null
  end;
  v_map record;
  v_email_user record;
  v_name_derived text;
  v_attendance_key text;
  v_raw_key text;
  v_resolved boolean := false;
begin
  if v_employee_name = '' and v_employee_id_raw <> '' then
    v_name_derived := trim(regexp_replace(v_employee_id_raw, '\s+E[0-9A-Za-z]+\s*$', '', 'i'));
    if v_name_derived <> '' then
      v_employee_name := v_name_derived;
    end if;
  end if;

  if (v_department = '' or v_employee_name = '') and v_employee_id_code <> '' then
    select m.department, m.employeename, m.email
    into v_map
    from public.zoho_people_user_map m
    where m.active = true
      and (
        lower(trim(m.employeeid)) = lower(trim(v_employee_id_code))
        or lower(trim(m.employeeid)) = lower(trim(v_employee_id_raw))
      )
    limit 1;

    if found then
      if v_department = '' then v_department := coalesce(v_map.department, ''); end if;
      if v_employee_name = '' then v_employee_name := coalesce(v_map.employeename, ''); end if;
      if v_employee_email = '' then v_employee_email := coalesce(v_map.email, ''); end if;
    end if;
  end if;

  if (v_department = '' or v_employee_name = '') and v_employee_email <> '' then
    select u.department, u.employee_name
    into v_email_user
    from public.users_directory u
    where u.active = true
      and lower(trim(coalesce(u.email, ''))) = lower(trim(v_employee_email))
    limit 1;

    if found then
      if v_department = '' then v_department := coalesce(v_email_user.department, ''); end if;
      if v_employee_name = '' then v_employee_name := coalesce(v_email_user.employee_name, ''); end if;
    end if;
  end if;

  -- Final fallback for Zoho rows that only have "EmployeeID" (name + code) but no department/email.
  if v_department = '' and v_employee_name <> '' then
    select s.department, s.employee_name
    into v_department, v_employee_name
    from (
      select
        u.department,
        u.employee_name,
        case
          when lower(trim(u.employee_name)) = lower(trim(v_employee_name)) then 1
          when lower(trim(u.employee_name)) like lower(trim(v_employee_name)) || '%' then 2
          when lower(trim(v_employee_name)) like lower(trim(u.employee_name)) || '%' then 2
          else 99
        end as score
      from public.users_directory u
      where u.active = true
    ) s
    where s.score < 99
    order by s.score asc, s.employee_name asc
    limit 1;
    v_department := coalesce(v_department, '');
    v_employee_name := coalesce(v_employee_name, '');
  end if;

  if v_attendance_day is null then
    v_attendance_day := coalesce(
      case when v_from_time is null then null else (v_from_time at time zone 'Asia/Kolkata')::date end,
      case when v_to_time is null then null else (v_to_time at time zone 'Asia/Kolkata')::date end,
      (now() at time zone 'Asia/Kolkata')::date
    );
  end if;

  v_attendance_key := md5(
    coalesce(v_source, '') || '|' ||
    coalesce(v_attendance_day::text, '') || '|' ||
    lower(trim(coalesce(v_department, ''))) || '|' ||
    lower(trim(coalesce(v_employee_name, ''))) || '|' ||
    lower(trim(coalesce(v_employee_id_raw, ''))) || '|' ||
    coalesce(v_payload->>'FromTime', v_payload->>'fromTime', v_payload->>'loginTime', '') || '|' ||
    coalesce(v_payload->>'ToTime', v_payload->>'toTime', v_payload->>'logoutTime', '')
  );

  v_raw_key := md5(
    coalesce(v_payload->>'orgID', '') || '|' ||
    coalesce(v_payload->>'id', '') || '|' ||
    coalesce(v_payload->>'AttendanceDay', v_payload->>'attendanceDay', '') || '|' ||
    coalesce(v_payload->>'EmployeeID', v_payload->>'employeeId', '') || '|' ||
    coalesce(v_payload->>'FromTime', v_payload->>'fromTime', v_payload->>'loginTime', '') || '|' ||
    coalesce(v_payload->>'ToTime', v_payload->>'toTime', v_payload->>'logoutTime', '')
  );

  v_resolved := (coalesce(v_department, '') <> '' and coalesce(v_employee_name, '') <> '');

  insert into public.zoho_people_attendance_raw (
    raw_key,
    "Status",
    "OverTime",
    "Description",
    "TotalHours",
    "orgID",
    "ExpectedToTime",
    "WorkingHours",
    "ToTime",
    "InputType",
    "form",
    "isdebug",
    "ExpectedFromTime",
    "id",
    "AttendanceDay",
    "DeviationTime",
    "EmployeeID",
    "BreakTime",
    "FromTime",
    payload_json,
    mapped,
    mapped_department,
    mapped_employee_name,
    received_at,
    updated_at
  ) values (
    v_raw_key,
    nullif(v_payload->>'Status', ''),
    nullif(v_payload->>'OverTime', ''),
    nullif(v_payload->>'Description', ''),
    nullif(v_payload->>'TotalHours', ''),
    v_org_id,
    nullif(v_payload->>'ExpectedToTime', ''),
    nullif(v_payload->>'WorkingHours', ''),
    nullif(v_payload->>'ToTime', ''),
    v_input_type,
    nullif(v_payload->>'form', ''),
    v_isdebug,
    nullif(v_payload->>'ExpectedFromTime', ''),
    v_record_id,
    nullif(v_payload->>'AttendanceDay', ''),
    nullif(v_payload->>'DeviationTime', ''),
    nullif(v_payload->>'EmployeeID', ''),
    nullif(v_payload->>'BreakTime', ''),
    nullif(v_payload->>'FromTime', ''),
    v_payload,
    v_resolved,
    nullif(v_department, ''),
    nullif(v_employee_name, ''),
    now(),
    now()
  )
  on conflict (raw_key) do update set
    "Status" = excluded."Status",
    "OverTime" = excluded."OverTime",
    "Description" = excluded."Description",
    "TotalHours" = excluded."TotalHours",
    "orgID" = excluded."orgID",
    "ExpectedToTime" = excluded."ExpectedToTime",
    "WorkingHours" = excluded."WorkingHours",
    "ToTime" = excluded."ToTime",
    "InputType" = excluded."InputType",
    "form" = excluded."form",
    "isdebug" = excluded."isdebug",
    "ExpectedFromTime" = excluded."ExpectedFromTime",
    "id" = excluded."id",
    "AttendanceDay" = excluded."AttendanceDay",
    "DeviationTime" = excluded."DeviationTime",
    "EmployeeID" = excluded."EmployeeID",
    "BreakTime" = excluded."BreakTime",
    "FromTime" = excluded."FromTime",
    payload_json = excluded.payload_json,
    mapped = excluded.mapped,
    mapped_department = excluded.mapped_department,
    mapped_employee_name = excluded.mapped_employee_name,
    updated_at = now();

  insert into public.user_attendance_logs (
    attendance_key,
    source,
    org_id,
    attendance_day,
    department,
    employee_name,
    employee_email,
    employee_id_raw,
    employee_id_code,
    status,
    from_time,
    to_time,
    working_minutes,
    total_minutes,
    break_minutes,
    over_time_minutes,
    input_type,
    raw_payload,
    ingested_at,
    updated_at
  ) values (
    v_attendance_key,
    case when v_source = '' then 'zoho_people' else v_source end,
    v_org_id,
    v_attendance_day,
    nullif(v_department, ''),
    nullif(v_employee_name, ''),
    nullif(v_employee_email, ''),
    nullif(v_employee_id_raw, ''),
    nullif(v_employee_id_code, ''),
    nullif(v_status, ''),
    v_from_time,
    v_to_time,
    v_working_minutes,
    v_total_minutes,
    v_break_minutes,
    v_over_time_minutes,
    v_input_type,
    v_payload,
    now(),
    now()
  )
  on conflict (attendance_key) do update set
    source = excluded.source,
    org_id = excluded.org_id,
    attendance_day = excluded.attendance_day,
    department = excluded.department,
    employee_name = excluded.employee_name,
    employee_email = excluded.employee_email,
    employee_id_raw = excluded.employee_id_raw,
    employee_id_code = excluded.employee_id_code,
    status = excluded.status,
    from_time = excluded.from_time,
    to_time = excluded.to_time,
    working_minutes = excluded.working_minutes,
    total_minutes = excluded.total_minutes,
    break_minutes = excluded.break_minutes,
    over_time_minutes = excluded.over_time_minutes,
    input_type = excluded.input_type,
    raw_payload = excluded.raw_payload,
    updated_at = now();

  return jsonb_build_object(
    'ok', true,
    'attendanceDay', v_attendance_day::text,
    'department', coalesce(v_department, ''),
    'employeeName', coalesce(v_employee_name, ''),
    'employeeIdCode', coalesce(v_employee_id_code, ''),
    'resolved', v_resolved,
    'rawKey', v_raw_key,
    'attendanceKey', v_attendance_key
  );
end;
$$;

create or replace function public.internal_reprocess_zoho_people_attendance_raw(p_payload jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit int := least(5000, greatest(1, coalesce(nullif(p_payload->>'limit','')::int, 500)));
  v_include_mapped boolean := case lower(coalesce(p_payload->>'includeMapped','false'))
    when 'true' then true
    when '1' then true
    when 'yes' then true
    else false
  end;
  v_reprocessed int := 0;
  v_resolved int := 0;
  r record;
  v_res jsonb;
  v_payload jsonb;
begin
  for r in
    select
      payload_json,
      "Status",
      "OverTime",
      "Description",
      "TotalHours",
      "orgID",
      "ExpectedToTime",
      "WorkingHours",
      "ToTime",
      "InputType",
      "form",
      "isdebug",
      "ExpectedFromTime",
      "id",
      "AttendanceDay",
      "DeviationTime",
      "EmployeeID",
      "BreakTime",
      "FromTime"
    from public.zoho_people_attendance_raw
    where v_include_mapped or coalesce(mapped, false) = false
    order by received_at asc
    limit v_limit
  loop
    v_payload := coalesce(r.payload_json, '{}'::jsonb) || jsonb_strip_nulls(jsonb_build_object(
      'Status', r."Status",
      'OverTime', r."OverTime",
      'Description', r."Description",
      'TotalHours', r."TotalHours",
      'orgID', r."orgID",
      'ExpectedToTime', r."ExpectedToTime",
      'WorkingHours', r."WorkingHours",
      'ToTime', r."ToTime",
      'InputType', r."InputType",
      'form', r."form",
      'isdebug', r."isdebug",
      'ExpectedFromTime', r."ExpectedFromTime",
      'id', r."id",
      'AttendanceDay', r."AttendanceDay",
      'DeviationTime', r."DeviationTime",
      'EmployeeID', r."EmployeeID",
      'BreakTime', r."BreakTime",
      'FromTime', r."FromTime"
    ));

    v_res := public.internal_ingest_zoho_people_attendance(v_payload);
    v_reprocessed := v_reprocessed + 1;
    if coalesce((v_res->>'resolved')::boolean, false) then
      v_resolved := v_resolved + 1;
    end if;
  end loop;

  return jsonb_build_object(
    'ok', true,
    'processed', v_reprocessed,
    'resolved', v_resolved
  );
end;
$$;

create or replace function public.internal_sync_zoho_people_user_map(p_payload jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit int := least(20000, greatest(1, coalesce(nullif(p_payload->>'limit','')::int, 5000)));
  v_upserted int := 0;
begin
  with unique_first_names as (
    select
      lower(split_part(trim(u.employee_name), ' ', 1)) as first_name_key
    from public.users_directory u
    where u.active = true
      and trim(coalesce(u.employee_name, '')) <> ''
    group by 1
    having count(*) = 1
  ),
  raw_candidates as (
    select
      public.extract_employee_id_code(r."EmployeeID") as employeeid,
      trim(regexp_replace(coalesce(r."EmployeeID", ''), '\s+E[0-9A-Za-z]+\s*$', '', 'i')) as raw_name,
      max(r.received_at) as last_seen_at
    from public.zoho_people_attendance_raw r
    where trim(coalesce(r."EmployeeID", '')) <> ''
    group by 1, 2
    having public.extract_employee_id_code(r."EmployeeID") <> ''
    order by max(r.received_at) desc
    limit v_limit
  ),
  scored as (
    select
      rc.employeeid,
      u.department,
      u.employee_name as employeename,
      coalesce(u.email, '') as email,
      rc.last_seen_at,
      case
        when lower(trim(u.employee_name)) = lower(trim(rc.raw_name)) then 1
        when lower(trim(u.employee_name)) like lower(trim(rc.raw_name)) || '%' then 2
        when lower(trim(rc.raw_name)) like lower(trim(u.employee_name)) || '%' then 2
        when lower(split_part(trim(u.employee_name), ' ', 1)) = lower(split_part(trim(rc.raw_name), ' ', 1))
             and exists (
               select 1
               from unique_first_names uf
               where uf.first_name_key = lower(split_part(trim(u.employee_name), ' ', 1))
             ) then 3
        else 99
      end as score
    from raw_candidates rc
    join public.users_directory u
      on u.active = true
     and (
       lower(trim(u.employee_name)) = lower(trim(rc.raw_name))
       or lower(trim(u.employee_name)) like lower(trim(rc.raw_name)) || '%'
       or lower(trim(rc.raw_name)) like lower(trim(u.employee_name)) || '%'
       or (
         lower(split_part(trim(u.employee_name), ' ', 1)) = lower(split_part(trim(rc.raw_name), ' ', 1))
         and exists (
           select 1
           from unique_first_names uf
           where uf.first_name_key = lower(split_part(trim(u.employee_name), ' ', 1))
         )
       )
     )
  ),
  best as (
    select
      s.employeeid,
      s.department,
      s.employeename,
      s.email
    from (
      select
        s.*,
        row_number() over (
          partition by s.employeeid
          order by s.score asc, s.last_seen_at desc, s.employeename asc
        ) as rn
      from scored s
      where s.score < 99
    ) s
    where s.rn = 1
  ),
  upserted as (
    insert into public.zoho_people_user_map (
      employee_id_code,
      department,
      employee_name,
      employee_email,
      updated_at,
      employeeid,
      employeename,
      email,
      active,
      updatedat,
      source
    )
    select
      b.employeeid,
      b.department,
      b.employeename,
      b.email,
      now(),
      b.employeeid,
      b.employeename,
      b.email,
      true,
      now(),
      'auto-sync-from-raw'
    from best b
    on conflict (employeeid) do update set
      employee_id_code = excluded.employee_id_code,
      department = excluded.department,
      employee_name = excluded.employee_name,
      employee_email = excluded.employee_email,
      updated_at = now(),
      employeename = excluded.employeename,
      email = excluded.email,
      active = true,
      updatedat = now(),
      source = excluded.source
    returning 1
  )
  select count(*)::int into v_upserted from upserted;

  return jsonb_build_object(
    'ok', true,
    'upserted', v_upserted
  );
end;
$$;

grant execute on function public.rpc_get_user_attendance(jsonb) to anon, authenticated;

revoke execute on function public.internal_ingest_zoho_people_attendance(jsonb) from public, anon, authenticated;
revoke execute on function public.internal_reprocess_zoho_people_attendance_raw(jsonb) from public, anon, authenticated;
revoke execute on function public.internal_sync_zoho_people_user_map(jsonb) from public, anon, authenticated;
